# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 MessageFoundry Organization and contributors
"""HL7 v2.5.1 message-structure metadata for the Steps-view field picker (ADR 0104 §2.3 P2/P3).

The picker scopes/ranks its segment list by the *message structure* a handler handles, and (P3) badges
each offered field/component path by whether it round-trips on both parser backends. Both need data that
``ide/media/hl7schema.json`` (segment-keyed) does not carry, so this module derives it from **hl7apy**
(the strict-validation catalog, version-pinned to 2.5.1) and the ``messagefoundry generate`` estate:

* **trigger -> structure** (``build_trigger_map``): a ``"CODE^TRIGGER" -> structure`` map. HL7 collapses
  many triggers onto one structure (``ADT^A04``/``A08``/``A13`` are all ``ADT_A01``), and hl7apy keys
  validation by structure — so a naive ``ADT^A08`` lookup misses. The map is the union of (a) the identity
  inversion of every hl7apy ``CODE_TRIGGER`` structure key and (b) the authoritative ADT collapse map
  (:data:`TRIGGER_TO_STRUCTURE`, the single source ``generators/adt.py`` also imports).
* **structure -> segments** (:func:`structure_segments`): a ``kind``-gated walk of hl7apy's ``MESSAGES``
  sequence — recurse into ``GRP`` nodes, collect ``SEG`` node ids, dedup preserving first-seen order.

:func:`to_json` emits the bundled ``ide/media/hl7structures.json`` artifact (regenerated by the
``messagefoundry hl7structures`` CLI). A byte-equal CI test keeps the committed bundle in sync with this
code (the ``requirements.lock`` discipline) so a stale bundle can never ship wrong scope/badges.
"""

from __future__ import annotations

from hl7apy.v2_5_1 import MESSAGES

#: The version this metadata is pinned to (hl7apy ``v2_5_1``). Surfaced in the artifact + the picker badge
#: so a differently-versioned strict inbound reads the scope/verified data as a pinned superset, not a
#: per-feed schema.
SUPPORTED_VERSION = "2.5.1"

# Trigger event -> 2.5.1 message structure (HL7 Chapter 3). The 57 ADT triggers share 25 structures (e.g.
# A04/A08/A13 -> ADT_A01). This is the single source: generators/adt.py imports it from here.
TRIGGER_TO_STRUCTURE: dict[str, str] = {
    "A01": "ADT_A01",
    "A04": "ADT_A01",
    "A08": "ADT_A01",
    "A13": "ADT_A01",
    "A02": "ADT_A02",
    "A03": "ADT_A03",
    "A05": "ADT_A05",
    "A14": "ADT_A05",
    "A28": "ADT_A05",
    "A31": "ADT_A05",
    "A06": "ADT_A06",
    "A07": "ADT_A06",
    "A09": "ADT_A09",
    "A10": "ADT_A09",
    "A11": "ADT_A09",
    "A12": "ADT_A12",
    "A15": "ADT_A15",
    "A16": "ADT_A16",
    "A17": "ADT_A17",
    "A18": "ADT_A18",
    "A20": "ADT_A20",
    "A21": "ADT_A21",
    "A22": "ADT_A21",
    "A23": "ADT_A21",
    "A25": "ADT_A21",
    "A26": "ADT_A21",
    "A27": "ADT_A21",
    "A29": "ADT_A21",
    "A32": "ADT_A21",
    "A33": "ADT_A21",
    "A24": "ADT_A24",
    "A30": "ADT_A30",
    "A34": "ADT_A30",
    "A35": "ADT_A30",
    "A36": "ADT_A30",
    "A46": "ADT_A30",
    "A47": "ADT_A30",
    "A48": "ADT_A30",
    "A49": "ADT_A30",
    "A37": "ADT_A37",
    "A38": "ADT_A38",
    "A39": "ADT_A39",
    "A40": "ADT_A39",
    "A41": "ADT_A39",
    "A42": "ADT_A39",
    "A43": "ADT_A43",
    "A44": "ADT_A43",
    "A45": "ADT_A45",
    "A50": "ADT_A50",
    "A51": "ADT_A50",
    "A52": "ADT_A52",
    "A53": "ADT_A52",
    "A54": "ADT_A54",
    "A55": "ADT_A54",
    "A60": "ADT_A60",
    "A61": "ADT_A61",
    "A62": "ADT_A61",
}


def build_trigger_map() -> dict[str, str]:
    """A ``"CODE^TRIGGER" -> structure id`` map for resolving a handler's declared/inferred message type.

    Union of (a) the **identity inversion** of every hl7apy ``CODE_TRIGGER`` structure key (so ``ORU^R01``
    -> ``ORU_R01``, ``SIU^S12`` -> ``SIU_S12``, … resolve without any per-generator import) and (b) the
    authoritative **ADT collapse** map (:data:`TRIGGER_TO_STRUCTURE`), applied last so a collapsed ADT
    trigger (``ADT^A08`` -> ``ADT_A01``) wins. A trigger with no entry resolves to ``None`` (generic scope)
    — never a *wrong* existing structure."""
    trig: dict[str, str] = {}
    for key in MESSAGES:
        code, sep, trigger = key.partition("_")
        if sep and code and trigger:
            trig[f"{code}^{trigger}"] = key
    for trigger, struct in TRIGGER_TO_STRUCTURE.items():
        trig[f"ADT^{trigger}"] = struct
    return trig


def resolve_structure(code: str | None, trigger: str | None) -> str | None:
    """The structure id for ``CODE^TRIGGER``, or ``None`` if unresolvable (→ generic, unscoped picker).

    A code-only type (no trigger) is unresolvable here (a code maps to many structures); the picker then
    offers the generic segment list. A caller that already knows the structure (an explicit 3-component
    ``"ADT^A01^ADT_A05"`` spec) uses that id directly and never calls this."""
    if not code or not trigger:
        return None
    return build_trigger_map().get(f"{code}^{trigger}")


def structure_segments(struct: str) -> list[str]:
    """The ordered, de-duplicated segment ids of message structure ``struct`` (``[]`` if unknown).

    Walks hl7apy's ``MESSAGES[struct] = ('sequence', (entries...))`` where each entry is
    ``(node_id, child, cardinality, kind)``: recurse into a ``GRP`` child, collect a ``SEG``'s ``node_id``
    (never descend a segment's field sequence), preserving first-seen order (a structure may repeat a
    segment — e.g. ``ADT_A01`` has ``ROL`` several times — which is deduped)."""
    if struct not in MESSAGES:
        return []
    seen: list[str] = []

    def walk(sequence: tuple[object, ...]) -> None:
        entries = sequence[1]
        assert isinstance(entries, tuple)
        for entry in entries:
            node_id, child, _cardinality, kind = entry
            if kind == "GRP":
                walk(child)
            elif kind == "SEG" and node_id not in seen:
                seen.append(node_id)

    walk(MESSAGES[struct])
    return seen


# --- P3: round-trip-verified paths -------------------------------------------

#: A fixed, delimiter-free ASCII token written at a candidate path to probe the round trip. Pinned in the
#: artifact so a reader knows exactly what was set.
SENTINEL = "MFRT0"

#: A minimal MSH the fixtures share (its own MSH-9 = ADT^A01 — arbitrary; the probe never reads it).
_MSH = "MSH|^~\\&|A|B|C|D|20200101||ADT^A01|1|P|2.5.1"


def _fixture(segment: str) -> str:
    """A minimal message that CONTAINS ``segment`` (seeded with one empty field) so ``set()`` can extend
    it rather than raise ``KeyError`` on an absent segment."""
    return _MSH if segment == "MSH" else f"{_MSH}\r{segment}|"


def _path_verified(fixture: str, path: str) -> bool:
    """Whether ``path`` round-trips on BOTH parser backends: ``set(path, SENTINEL) -> encode() -> read
    back == SENTINEL`` on the built-in AND python-hl7 backends, and the two encodings agree byte-for-byte
    (a dormant parser-parity regression guard — NOT the round-trip proof, which is the read-back)."""
    from messagefoundry.parsing._backend import backend
    from messagefoundry.parsing.message import Message

    encodings: list[str] = []
    for builtin in (True, False):
        with backend(builtin=builtin):
            try:
                msg = Message.parse(fixture)
                msg.set(path, SENTINEL)
                encoded = msg.encode()
                read_back = Message.parse(encoded).field(path)
            except (KeyError, ValueError):
                return False  # padding limits / an unsettable path -> unverified (degrades to free-text)
        if read_back != SENTINEL:
            return False
        encodings.append(encoded)
    return encodings[0] == encodings[1]


def verified_paths() -> dict[str, dict[str, list[int] | list[str]]]:
    """Segment-keyed round-trip-verified paths for the picker's P3 badge — ``{seg: {"fields":[…],
    "components":["f.c",…]}}``. Verification is per-segment (independent of the enclosing structure), so a
    path proven once is proven for every structure. **Build-time** by design: the ``backend()`` switch
    flips a module-global read per-parse, so running this inside the async engine would corrupt concurrent
    parses — here it runs single-threaded (~<1 s over the whole schema). MSH-1/MSH-2 (the encoding-character
    fields) are structurally excluded — they are never value targets."""
    from messagefoundry.hl7schema import hl7_schema

    schema = hl7_schema()
    out: dict[str, dict[str, list[int] | list[str]]] = {}
    for seg, segdef in schema["segments"].items():
        fixture = _fixture(seg)
        fields: list[int] = []
        components: list[str] = []
        for field in segdef["fields"]:
            fi = field["index"]
            if seg == "MSH" and fi in (1, 2):
                continue  # MSH-1/MSH-2 are the encoding characters — never a value target
            if _path_verified(fixture, f"{seg}-{fi}"):
                fields.append(fi)
            for comp in field["components"]:
                if _path_verified(fixture, f"{seg}-{fi}.{comp['index']}"):
                    components.append(f"{fi}.{comp['index']}")
        out[seg] = {"fields": fields, "components": components}
    return out


def to_json() -> dict[str, object]:
    """The bundled ``ide/media/hl7structures.json`` payload (P2 ``triggerToStructure``/``structureSegments``
    + P3 ``verified``).

    Everything is sorted so the artifact is deterministic (the CI byte-equal sync test depends on it)."""
    trig = build_trigger_map()
    structures = sorted(set(trig.values()))
    return {
        "version": SUPPORTED_VERSION,
        "sentinel": SENTINEL,
        "triggerToStructure": dict(sorted(trig.items())),
        "structureSegments": {s: structure_segments(s) for s in structures},
        "verified": verified_paths(),
    }
