// "Set Up Version Control & Checks" — a guided, offline, provider-agnostic flow that puts a
// code-first MessageFoundry project under git and wires a local pre-commit hook running
// `messagefoundry check`. Leans on the user's git (respecting an existing repo); never contacts a
// network. Scaffold templates are inline string consts (esbuild bundles only TS, not loose assets).
import * as fs from "node:fs";
import * as path from "node:path";
import * as vscode from "vscode";
import { configDir, messageSetsDir, workspaceDir } from "./cli";
import { findGit, getHooksPath, git, isRepo } from "./git";

const GITIGNORE_MARKER = "# --- MessageFoundry ---";
// Kept deliberately minimal; NOTE we do NOT ignore .vscode/ (so a team shares messagefoundry.*
// settings) or samples/messages (fixtures must be committed for the dry-run gate to run).
const GITIGNORE_ENTRIES = [
  ".mefor/", // dev store dir
  "*.db*", // sqlite db + -wal/-shm
  "out/", // sample file-outbound target
  "*.log",
  "__pycache__/",
  ".venv/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".pytest_cache/",
  ".DS_Store",
  "Thumbs.db",
];

const GITATTRIBUTES_LINE = ".mefor-hooks/** text eol=lf";
const HOOKS_DIR = ".mefor-hooks";
const HOOK_REL = `${HOOKS_DIR}/pre-commit`;

// POSIX hook (Git for Windows runs it via bundled sh). Fails OPEN when Python / the package isn't
// available (a non-developer checkout shouldn't be blocked), fails CLOSED on a bad config (the
// `check` exit code propagates via exec). __CONFIG_DIR__/__MESSAGES_DIR__ are templated at setup.
const PRE_COMMIT_TEMPLATE = `#!/bin/sh
# MessageFoundry pre-commit checks — generated by the VS Code extension.
# Runs \`messagefoundry check\` so a commit can't introduce a broken config.
# Bypass once with: git commit --no-verify

PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found; skipping checks." >&2
  exit 0
fi

# Prefer a project virtualenv if present (Windows + POSIX layouts).
if [ -x ".venv/Scripts/python.exe" ]; then
  PY=".venv/Scripts/python.exe"
elif [ -x ".venv/bin/python" ]; then
  PY=".venv/bin/python"
fi

if ! "$PY" -c "import messagefoundry" >/dev/null 2>&1; then
  echo "MessageFoundry: 'messagefoundry' not importable in this environment; skipping checks." >&2
  exit 0
fi

exec "$PY" -m messagefoundry check --config __CONFIG_DIR__ --messages __MESSAGES_DIR__
`;

const DISMISS_KEY = "messagefoundry.scPromptDismissed";

let channel: vscode.OutputChannel | undefined;
function out(): vscode.OutputChannel {
  channel ??= vscode.window.createOutputChannel("MessageFoundry Checks");
  return channel;
}

/** One-time, dismissible nudge: offer setup when there are config modules but no repo yet. */
export async function maybeSuggestSourceControl(context: vscode.ExtensionContext): Promise<void> {
  const ws = workspaceDir();
  if (!ws) {
    return;
  }
  if (!vscode.workspace.getConfiguration("messagefoundry").get<boolean>("sourceControl.autoPrompt", true)) {
    return;
  }
  if (
    context.globalState.get<boolean>(DISMISS_KEY) ||
    context.workspaceState.get<boolean>(DISMISS_KEY)
  ) {
    return;
  }
  if (await pathExists(path.join(ws, ".git"))) {
    return; // already under version control
  }
  const dir = configDir();
  if (!(await hasConfigModules(path.isAbsolute(dir) ? dir : path.join(ws, dir)))) {
    return; // not a MessageFoundry project (no config modules)
  }
  const pick = await vscode.window.showInformationMessage(
    "Put this MessageFoundry project under version control and run checks on every commit?",
    "Set it up",
    "Not now",
    "Don't ask again",
  );
  if (pick === "Set it up") {
    await setupSourceControl(context);
  } else if (pick === "Not now") {
    await context.workspaceState.update(DISMISS_KEY, true); // this project, this machine
  } else if (pick === "Don't ask again") {
    await context.globalState.update(DISMISS_KEY, true); // any project
  }
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(vscode.Uri.file(p));
    return true;
  } catch {
    return false;
  }
}

async function hasConfigModules(dir: string): Promise<boolean> {
  try {
    const entries = await vscode.workspace.fs.readDirectory(vscode.Uri.file(dir));
    return entries.some(
      ([name, type]) =>
        type === vscode.FileType.File && name.endsWith(".py") && !name.startsWith("_"),
    );
  } catch {
    return false;
  }
}

export async function setupSourceControl(_context: vscode.ExtensionContext): Promise<void> {
  const ws = workspaceDir();
  if (!ws) {
    void vscode.window.showErrorMessage("MessageFoundry: open a workspace folder first.");
    return;
  }

  const bin = await findGit();
  if (!bin) {
    await guideGitInstall();
    return;
  }

  // Respect an existing repo (don't re-init); otherwise offer to initialize locally.
  if (!(await isRepo(bin, ws))) {
    const pick = await vscode.window.showInformationMessage(
      "No git repository here yet. Initialize one? (Stays on this machine — no network.)",
      "Initialize",
      "Cancel",
    );
    if (pick !== "Initialize") {
      return;
    }
    let res = await git(bin, ["init", "-b", "main"], ws);
    if (res.code !== 0) {
      // Older git without `-b`: init, then best-effort rename the branch.
      res = await git(bin, ["init"], ws);
      if (res.code !== 0) {
        void vscode.window.showErrorMessage(`MessageFoundry: git init failed — ${res.stderr.trim()}`);
        return;
      }
      await git(bin, ["checkout", "-b", "main"], ws);
    }
  }

  const notes: string[] = [];
  notes.push(`.gitignore: ${await scaffoldGitignore(ws)}`);
  notes.push(`.gitattributes: ${await scaffoldGitattributes(ws)}`);
  notes.push(`hook: ${await scaffoldHook(bin, ws)}`);
  notes.push(`core.hooksPath: ${await wireHooksPath(bin, ws)}`);

  await maybeAddRemote(bin, ws);
  await maybeFirstCommit(bin, ws);

  out().appendLine("Set Up Version Control & Checks:");
  for (const n of notes) {
    out().appendLine(`  • ${n}`);
  }
  void vscode.window.showInformationMessage("MessageFoundry: version control & checks are set up.");
}

async function guideGitInstall(): Promise<void> {
  const choice = await vscode.window.showWarningMessage(
    "Git isn't installed (or wasn't found). Version control needs it — nothing leaves your machine.",
    "Install with winget",
    "Open git-scm.com",
    "Later",
  );
  if (choice === "Install with winget") {
    const term = vscode.window.createTerminal("Install Git");
    term.show();
    term.sendText("winget install --id Git.Git -e", false); // typed, not run — the user presses Enter
  } else if (choice === "Open git-scm.com") {
    await vscode.env.openExternal(vscode.Uri.parse("https://git-scm.com/downloads"));
  }
}

async function readFileOrEmpty(uri: vscode.Uri): Promise<string> {
  try {
    return Buffer.from(await vscode.workspace.fs.readFile(uri)).toString("utf8");
  } catch {
    return "";
  }
}

/** Append only the missing entries under a delimited block; never rewrite the user's content. */
async function scaffoldGitignore(ws: string): Promise<string> {
  const uri = vscode.Uri.file(path.join(ws, ".gitignore"));
  const existing = await readFileOrEmpty(uri);
  const present = new Set(existing.split(/\r?\n/).map((l) => l.trim()));
  const missing = GITIGNORE_ENTRIES.filter((e) => !present.has(e));
  if (missing.length === 0) {
    return "already up to date";
  }
  const sep = existing.length && !existing.endsWith("\n") ? "\n" : "";
  const header = existing.includes(GITIGNORE_MARKER) ? "" : `${GITIGNORE_MARKER}\n`;
  await vscode.workspace.fs.writeFile(
    uri,
    Buffer.from(`${existing}${sep}${header}${missing.join("\n")}\n`, "utf8"),
  );
  return `added ${missing.length} entr${missing.length === 1 ? "y" : "ies"}`;
}

/** Ensure the LF-eol rule for the hook exists (CRLF would break the `#!/bin/sh` shebang on Windows). */
async function scaffoldGitattributes(ws: string): Promise<string> {
  const uri = vscode.Uri.file(path.join(ws, ".gitattributes"));
  const existing = await readFileOrEmpty(uri);
  const present = new Set(existing.split(/\r?\n/).map((l) => l.trim()));
  if (present.has(GITATTRIBUTES_LINE)) {
    return "already up to date";
  }
  const sep = existing.length && !existing.endsWith("\n") ? "\n" : "";
  await vscode.workspace.fs.writeFile(
    uri,
    Buffer.from(`${existing}${sep}${GITATTRIBUTES_LINE}\n`, "utf8"),
  );
  return "added LF rule";
}

// POSIX single-quote a value for safe embedding in the generated /bin/sh hook. `configDir`/
// `messageSetsDir` are window-scoped settings a checked-in `.vscode/settings.json` can supply, so a
// crafted value (e.g. `"; rm -rf ~ #`) must not break out of its argument and run arbitrary shell on
// the next `git commit`. Single quotes disable every sh metacharacter; an embedded `'` is closed,
// escaped as `\'`, and reopened.
function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

async function scaffoldHook(bin: string, ws: string): Promise<string> {
  // Function replacements (not string ones) — a string replacement would interpret `$`-sequences
  // (e.g. `$'`) in the quoted value, re-injecting unescaped text.
  const hook = PRE_COMMIT_TEMPLATE.replace(
    /__CONFIG_DIR__/g,
    () => shSingleQuote(configDir()),
  ).replace(/__MESSAGES_DIR__/g, () => shSingleQuote(messageSetsDir()));
  const hookPath = path.join(ws, HOOKS_DIR, "pre-commit");
  await vscode.workspace.fs.createDirectory(vscode.Uri.file(path.join(ws, HOOKS_DIR)));
  await vscode.workspace.fs.writeFile(vscode.Uri.file(hookPath), Buffer.from(hook, "utf8"));
  fs.chmodSync(hookPath, 0o755);
  // Record the exec bit in git so it survives a clone on macOS/Linux (Windows FS has no x bit).
  // update-index --chmod needs the path in the index, so add it first.
  await git(bin, ["add", HOOK_REL, ".gitattributes"], ws);
  await git(bin, ["update-index", "--chmod=+x", HOOK_REL], ws);
  return "written (.mefor-hooks/pre-commit, +x)";
}

/** Point git at the hook only if safe: don't clobber a user's existing hooksPath or real hook. */
async function wireHooksPath(bin: string, ws: string): Promise<string> {
  const current = await getHooksPath(bin, ws);
  if (current === HOOKS_DIR) {
    return "already set";
  }
  if (current) {
    void vscode.window.showWarningMessage(
      `MessageFoundry: core.hooksPath is already '${current}'. Left as-is — point it at '${HOOKS_DIR}' to enable checks.`,
    );
    return `left as '${current}' (not clobbered)`;
  }
  const realHook = vscode.Uri.file(path.join(ws, ".git", "hooks", "pre-commit"));
  try {
    await vscode.workspace.fs.stat(realHook);
    void vscode.window.showWarningMessage(
      "MessageFoundry: an existing .git/hooks/pre-commit was found. Left it alone — remove or merge it, then re-run setup.",
    );
    return "not set (existing .git/hooks/pre-commit)";
  } catch {
    // no existing real hook — safe to set
  }
  const res = await git(bin, ["config", "core.hooksPath", HOOKS_DIR], ws);
  return res.code === 0 ? `set to '${HOOKS_DIR}'` : `failed: ${res.stderr.trim()}`;
}

async function maybeAddRemote(bin: string, ws: string): Promise<void> {
  const remotes = (await git(bin, ["remote"], ws)).stdout.split(/\r?\n/).map((r) => r.trim());
  if (remotes.includes("origin")) {
    return; // respect an existing remote
  }
  const pick = await vscode.window.showQuickPick(
    [
      { label: "Skip — local only (recommended)", add: false },
      { label: "Add a remote…", add: true },
    ],
    { placeHolder: "Add a remote? Nothing is contacted now — you push later from Source Control." },
  );
  if (!pick?.add) {
    return;
  }
  const url = await vscode.window.showInputBox({
    prompt: "Remote URL or path — any host, scp-style, or a local/UNC bare path (never GitHub-specific)",
    placeHolder: "https://… · git@host:repo.git · /srv/git/proj.git · \\\\server\\repos\\proj.git",
  });
  if (!url?.trim()) {
    return;
  }
  const res = await git(bin, ["remote", "add", "origin", url.trim()], ws);
  if (res.code !== 0) {
    void vscode.window.showErrorMessage(`MessageFoundry: could not add remote — ${res.stderr.trim()}`);
    return;
  }
  void vscode.window.showInformationMessage(
    "MessageFoundry: remote 'origin' added. Push later via the Source Control view (nothing was sent).",
  );
}

async function maybeFirstCommit(bin: string, ws: string): Promise<void> {
  const pick = await vscode.window.showInformationMessage(
    "Make the first commit now? The MessageFoundry checks will run so you can watch them pass.",
    "Commit now",
    "Skip",
  );
  if (pick !== "Commit now") {
    return;
  }
  await git(bin, ["add", "-A"], ws);
  const res = await git(
    bin,
    ["commit", "-m", "Initial commit (MessageFoundry checks enabled)"],
    ws,
  );
  out().appendLine("--- first commit ---");
  if (res.stdout.trim()) {
    out().appendLine(res.stdout.trim());
  }
  if (res.stderr.trim()) {
    out().appendLine(res.stderr.trim());
  }
  if (res.code === 0) {
    void vscode.window.showInformationMessage("MessageFoundry: first commit created — checks passed. ✓");
  } else {
    out().show();
    void vscode.window.showErrorMessage(
      "MessageFoundry: commit blocked by checks — see the 'MessageFoundry Checks' output. Bypass once with `git commit --no-verify`.",
    );
  }
}
