// "Set Up Version Control & Checks" — a guided, offline, provider-agnostic flow that puts a
// code-first MessageFoundry project under git and wires a local pre-commit hook running
// `messagefoundry check`. Leans on the user's git (respecting an existing repo); never contacts a
// network. Scaffold templates are inline string consts (esbuild bundles only TS, not loose assets).
import * as fs from "node:fs";
import * as path from "node:path";
import * as vscode from "vscode";
import { configDir, messageSetsDir, run, workspaceDir } from "./cli";
import { findGit, getHooksPath, getRemoteUrl, git, isRepo } from "./git";

const GITIGNORE_MARKER = "# --- MessageFoundry ---";
// Kept deliberately minimal; NOTE we do NOT ignore .vscode/ (so a team shares messagefoundry.*
// settings) or samples/messages (fixtures must be committed for the dry-run gate to run).
const GITIGNORE_ENTRIES = [
  ".mefor/", // dev store dir
  "*.db*", // sqlite db + -wal/-shm
  "out/", // sample file-outbound target
  "*.log",
  "__pycache__/",
  ".venv/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".pytest_cache/",
  ".DS_Store",
  "Thumbs.db",
];

const GITATTRIBUTES_LINE = ".mefor-hooks/** text eol=lf";
const HOOKS_DIR = ".mefor-hooks";
const HOOK_REL = `${HOOKS_DIR}/pre-commit`;

// POSIX hook (Git for Windows runs it via bundled sh). Fails OPEN when Python / the package isn't
// available (a non-developer checkout shouldn't be blocked), fails CLOSED on a bad config (the
// `check` exit code propagates via exec). __CONFIG_DIR__/__MESSAGES_DIR__ are templated at setup.
const PRE_COMMIT_TEMPLATE = `#!/bin/sh
# MessageFoundry pre-commit checks — generated by the VS Code extension.
# Runs \`messagefoundry check\` so a commit can't introduce a broken config.
# Bypass once with: git commit --no-verify

PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found; skipping checks." >&2
  exit 0
fi

# Prefer a project virtualenv if present (Windows + POSIX layouts).
if [ -x ".venv/Scripts/python.exe" ]; then
  PY=".venv/Scripts/python.exe"
elif [ -x ".venv/bin/python" ]; then
  PY=".venv/bin/python"
fi

if ! "$PY" -c "import messagefoundry" >/dev/null 2>&1; then
  echo "MessageFoundry: 'messagefoundry' not importable in this environment; skipping checks." >&2
  exit 0
fi

exec "$PY" -m messagefoundry check --config __CONFIG_DIR__ --messages __MESSAGES_DIR__
`;

const DISMISS_KEY = "messagefoundry.scPromptDismissed";

let channel: vscode.OutputChannel | undefined;
function out(): vscode.OutputChannel {
  channel ??= vscode.window.createOutputChannel("MessageFoundry Checks");
  return channel;
}

/** One-time, dismissible nudge: offer setup when there are config modules but no repo yet. */
export async function maybeSuggestSourceControl(context: vscode.ExtensionContext): Promise<void> {
  const ws = workspaceDir();
  if (!ws) {
    return;
  }
  if (!vscode.workspace.getConfiguration("messagefoundry").get<boolean>("sourceControl.autoPrompt", true)) {
    return;
  }
  if (
    context.globalState.get<boolean>(DISMISS_KEY) ||
    context.workspaceState.get<boolean>(DISMISS_KEY)
  ) {
    return;
  }
  if (await pathExists(path.join(ws, ".git"))) {
    return; // already under version control
  }
  const dir = configDir();
  if (!(await hasConfigModules(path.isAbsolute(dir) ? dir : path.join(ws, dir)))) {
    return; // not a MessageFoundry project (no config modules)
  }
  const pick = await vscode.window.showInformationMessage(
    "Put this MessageFoundry project under version control and run checks on every commit?",
    "Set it up",
    "Not now",
    "Don't ask again",
  );
  if (pick === "Set it up") {
    await setupSourceControl(context);
  } else if (pick === "Not now") {
    await context.workspaceState.update(DISMISS_KEY, true); // this project, this machine
  } else if (pick === "Don't ask again") {
    await context.globalState.update(DISMISS_KEY, true); // any project
  }
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await vscode.workspace.fs.stat(vscode.Uri.file(p));
    return true;
  } catch {
    return false;
  }
}

async function hasConfigModules(dir: string): Promise<boolean> {
  try {
    const entries = await vscode.workspace.fs.readDirectory(vscode.Uri.file(dir));
    return entries.some(
      ([name, type]) =>
        type === vscode.FileType.File && name.endsWith(".py") && !name.startsWith("_"),
    );
  } catch {
    return false;
  }
}

export async function setupSourceControl(_context: vscode.ExtensionContext): Promise<void> {
  const ws = workspaceDir();
  if (!ws) {
    void vscode.window.showErrorMessage("MessageFoundry: open a workspace folder first.");
    return;
  }

  const bin = await findGit();
  if (!bin) {
    await guideGitInstall();
    return;
  }

  // Respect an existing repo (don't re-init); otherwise offer to initialize locally.
  if (!(await isRepo(bin, ws))) {
    const pick = await vscode.window.showInformationMessage(
      "No git repository here yet. Initialize one? (Stays on this machine — no network.)",
      "Initialize",
      "Cancel",
    );
    if (pick !== "Initialize") {
      return;
    }
    let res = await git(bin, ["init", "-b", "main"], ws);
    if (res.code !== 0) {
      // Older git without `-b`: init, then best-effort rename the branch.
      res = await git(bin, ["init"], ws);
      if (res.code !== 0) {
        void vscode.window.showErrorMessage(`MessageFoundry: git init failed — ${res.stderr.trim()}`);
        return;
      }
      await git(bin, ["checkout", "-b", "main"], ws);
    }
  }

  const notes: string[] = [];
  notes.push(`.gitignore: ${await scaffoldGitignore(ws)}`);
  notes.push(`.gitattributes: ${await scaffoldGitattributes(ws)}`);
  notes.push(`hook: ${await scaffoldHook(bin, ws)}`);
  notes.push(`core.hooksPath: ${await wireHooksPath(bin, ws)}`);

  await maybeAddRemote(bin, ws);
  await maybeFirstCommit(bin, ws);

  out().appendLine("Set Up Version Control & Checks:");
  for (const n of notes) {
    out().appendLine(`  • ${n}`);
  }
  void vscode.window.showInformationMessage("MessageFoundry: version control & checks are set up.");
}

async function guideGitInstall(): Promise<void> {
  const choice = await vscode.window.showWarningMessage(
    "Git isn't installed (or wasn't found). Version control needs it — nothing leaves your machine.",
    "Install with winget",
    "Open git-scm.com",
    "Later",
  );
  if (choice === "Install with winget") {
    const term = vscode.window.createTerminal("Install Git");
    term.show();
    term.sendText("winget install --id Git.Git -e", false); // typed, not run — the user presses Enter
  } else if (choice === "Open git-scm.com") {
    await vscode.env.openExternal(vscode.Uri.parse("https://git-scm.com/downloads"));
  }
}

async function readFileOrEmpty(uri: vscode.Uri): Promise<string> {
  try {
    return Buffer.from(await vscode.workspace.fs.readFile(uri)).toString("utf8");
  } catch {
    return "";
  }
}

/** Append only the missing entries under a delimited block; never rewrite the user's content. */
async function scaffoldGitignore(ws: string): Promise<string> {
  const uri = vscode.Uri.file(path.join(ws, ".gitignore"));
  const existing = await readFileOrEmpty(uri);
  const present = new Set(existing.split(/\r?\n/).map((l) => l.trim()));
  const missing = GITIGNORE_ENTRIES.filter((e) => !present.has(e));
  if (missing.length === 0) {
    return "already up to date";
  }
  const sep = existing.length && !existing.endsWith("\n") ? "\n" : "";
  const header = existing.includes(GITIGNORE_MARKER) ? "" : `${GITIGNORE_MARKER}\n`;
  await vscode.workspace.fs.writeFile(
    uri,
    Buffer.from(`${existing}${sep}${header}${missing.join("\n")}\n`, "utf8"),
  );
  return `added ${missing.length} entr${missing.length === 1 ? "y" : "ies"}`;
}

/** Ensure the LF-eol rule for the hook exists (CRLF would break the `#!/bin/sh` shebang on Windows). */
async function scaffoldGitattributes(ws: string): Promise<string> {
  const uri = vscode.Uri.file(path.join(ws, ".gitattributes"));
  const existing = await readFileOrEmpty(uri);
  const present = new Set(existing.split(/\r?\n/).map((l) => l.trim()));
  if (present.has(GITATTRIBUTES_LINE)) {
    return "already up to date";
  }
  const sep = existing.length && !existing.endsWith("\n") ? "\n" : "";
  await vscode.workspace.fs.writeFile(
    uri,
    Buffer.from(`${existing}${sep}${GITATTRIBUTES_LINE}\n`, "utf8"),
  );
  return "added LF rule";
}

// POSIX single-quote a value for safe embedding in the generated /bin/sh hook. `configDir`/
// `messageSetsDir` are window-scoped settings a checked-in `.vscode/settings.json` can supply, so a
// crafted value (e.g. `"; rm -rf ~ #`) must not break out of its argument and run arbitrary shell on
// the next `git commit`. Single quotes disable every sh metacharacter; an embedded `'` is closed,
// escaped as `\'`, and reopened.
function shSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

async function scaffoldHook(bin: string, ws: string): Promise<string> {
  // Function replacements (not string ones) — a string replacement would interpret `$`-sequences
  // (e.g. `$'`) in the quoted value, re-injecting unescaped text.
  const hook = PRE_COMMIT_TEMPLATE.replace(
    /__CONFIG_DIR__/g,
    () => shSingleQuote(configDir()),
  ).replace(/__MESSAGES_DIR__/g, () => shSingleQuote(messageSetsDir()));
  const hookPath = path.join(ws, HOOKS_DIR, "pre-commit");
  await vscode.workspace.fs.createDirectory(vscode.Uri.file(path.join(ws, HOOKS_DIR)));
  await vscode.workspace.fs.writeFile(vscode.Uri.file(hookPath), Buffer.from(hook, "utf8"));
  fs.chmodSync(hookPath, 0o755);
  // Record the exec bit in git so it survives a clone on macOS/Linux (Windows FS has no x bit).
  // update-index --chmod needs the path in the index, so add it first.
  await git(bin, ["add", HOOK_REL, ".gitattributes"], ws);
  await git(bin, ["update-index", "--chmod=+x", HOOK_REL], ws);
  return "written (.mefor-hooks/pre-commit, +x)";
}

/** Point git at the hook only if safe: don't clobber a user's existing hooksPath or real hook. */
async function wireHooksPath(bin: string, ws: string): Promise<string> {
  const current = await getHooksPath(bin, ws);
  if (current === HOOKS_DIR) {
    return "already set";
  }
  if (current) {
    void vscode.window.showWarningMessage(
      `MessageFoundry: core.hooksPath is already '${current}'. Left as-is — point it at '${HOOKS_DIR}' to enable checks.`,
    );
    return `left as '${current}' (not clobbered)`;
  }
  const realHook = vscode.Uri.file(path.join(ws, ".git", "hooks", "pre-commit"));
  try {
    await vscode.workspace.fs.stat(realHook);
    void vscode.window.showWarningMessage(
      "MessageFoundry: an existing .git/hooks/pre-commit was found. Left it alone — remove or merge it, then re-run setup.",
    );
    return "not set (existing .git/hooks/pre-commit)";
  } catch {
    // no existing real hook — safe to set
  }
  const res = await git(bin, ["config", "core.hooksPath", HOOKS_DIR], ws);
  return res.code === 0 ? `set to '${HOOKS_DIR}'` : `failed: ${res.stderr.trim()}`;
}

// "Where should this config repo be stored?" — the setup-time storage choice. Local-only suits a
// single-box (non-HA) engine, dev, or air-gapped work with no server; a shared remote is the durable,
// team- and HA-friendly home (see docs/VERSION-CONTROL.md). Offline-safe: we only *configure* the
// 'origin' remote — nothing is fetched or pushed here (the user pushes later from Source Control).
async function maybeAddRemote(bin: string, ws: string): Promise<void> {
  if (await getRemoteUrl(bin, ws)) {
    return; // respect an existing 'origin' — the storage location is already chosen
  }
  const pick = await vscode.window.showQuickPick(
    [
      {
        label: "On this machine only",
        detail:
          "Keep the repo local — fine for a single-box (non-HA) engine, dev, or air-gapped work with no server. You can add a remote later.",
        remote: false,
      },
      {
        label: "Store on a shared remote…",
        detail:
          "Recommended for high availability (multiple engine hosts), a team of developers, or off-machine backup. Any git host, or a bare repo on a network share.",
        remote: true,
      },
    ],
    {
      placeHolder: "Where should this config repo be stored? Nothing is contacted now — you push later.",
      ignoreFocusOut: true,
    },
  );
  if (!pick?.remote) {
    return; // local only (or cancelled)
  }
  await promptAndSetRemote(bin, ws);
}

// Prompt for a remote URL/path and point 'origin' at it (add if absent, update if present). Never
// fetches or pushes — provider-agnostic (any host, scp-style, or a local/UNC bare path). Returns
// whether a remote was set.
async function promptAndSetRemote(bin: string, ws: string, current?: string): Promise<boolean> {
  const url = await vscode.window.showInputBox({
    prompt: "Remote URL or path — any host, scp-style, or a local/UNC bare path (never GitHub-specific)",
    placeHolder: "https://forgejo.example/org/cfg.git · git@host:repo.git · \\\\server\\repos\\cfg.git",
    value: current ?? "",
    ignoreFocusOut: true,
  });
  if (!url?.trim()) {
    return false;
  }
  const exists = Boolean(await getRemoteUrl(bin, ws));
  const res = exists
    ? await git(bin, ["remote", "set-url", "origin", url.trim()], ws)
    : await git(bin, ["remote", "add", "origin", url.trim()], ws);
  if (res.code !== 0) {
    void vscode.window.showErrorMessage(`MessageFoundry: could not set remote — ${res.stderr.trim()}`);
    return false;
  }
  void vscode.window.showInformationMessage(
    "MessageFoundry: remote 'origin' set. Push later via the Source Control view (nothing was sent).",
  );
  return true;
}

// "MessageFoundry: Config Repo Storage Location" — view or change where the config repo is stored,
// after setup. The git 'origin' remote IS the storage location (single source of truth — no separate
// MEFOR setting to drift from it). This is a small, offline-safe FORM over it (a webview panel, not a
// modal QuickPick chain) so the current location and the local-vs-remote choice are visible at once.
export async function setRepoStorage(): Promise<void> {
  const ws = workspaceDir();
  if (!ws) {
    void vscode.window.showErrorMessage("MessageFoundry: open a workspace folder first.");
    return;
  }
  const bin = await findGit();
  if (!bin) {
    await guideGitInstall();
    return;
  }
  if (!(await isRepo(bin, ws))) {
    const pick = await vscode.window.showInformationMessage(
      "This folder isn't under version control yet. Set it up first?",
      "Set Up Version Control & Checks",
      "Cancel",
    );
    if (pick === "Set Up Version Control & Checks") {
      await vscode.commands.executeCommand("messagefoundry.setupSourceControl");
    }
    return;
  }
  const current = (await getRemoteUrl(bin, ws)) ?? "";
  const panel = vscode.window.createWebviewPanel(
    "messagefoundry.repoStorage",
    "Config Repo Storage",
    vscode.ViewColumn.Active,
    { enableScripts: true },
  );
  panel.webview.html = renderRepoStorageHtml(current);
  panel.webview.onDidReceiveMessage(
    async (m: { command?: string; mode?: string; url?: string }) => {
      if (m.command === "cancel") {
        panel.dispose();
        return;
      }
      if (m.command !== "save") {
        return;
      }
      const hadRemote = Boolean(await getRemoteUrl(bin, ws));
      if (m.mode === "local") {
        if (hadRemote) {
          const res = await git(bin, ["remote", "remove", "origin"], ws);
          if (res.code !== 0) {
            panel.webview.postMessage({ command: "error", text: `Could not remove remote — ${res.stderr.trim()}` });
            return;
          }
          void vscode.window.showInformationMessage(
            "MessageFoundry: now local-only. Your history stays on this machine; nothing was deleted on the remote.",
          );
        } else {
          void vscode.window.showInformationMessage("MessageFoundry: storage stays local-only.");
        }
        panel.dispose();
        return;
      }
      // Shared remote: set-url if one exists, else add. Never fetches/pushes — provider-agnostic.
      const url = (m.url ?? "").trim();
      if (!url) {
        panel.webview.postMessage({ command: "error", text: "Enter a remote URL or path." });
        return;
      }
      const res = hadRemote
        ? await git(bin, ["remote", "set-url", "origin", url], ws)
        : await git(bin, ["remote", "add", "origin", url], ws);
      if (res.code !== 0) {
        panel.webview.postMessage({ command: "error", text: `Could not set remote — ${res.stderr.trim()}` });
        return;
      }
      void vscode.window.showInformationMessage(
        "MessageFoundry: remote 'origin' set. Push later via the Source Control view (nothing was sent).",
      );
      panel.dispose();
    },
  );
}

function scNonce(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let s = "";
  for (let i = 0; i < 24; i++) {
    s += chars[Math.floor(Math.random() * chars.length)];
  }
  return s;
}

function scEscape(v: string): string {
  return v
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderRepoStorageHtml(current: string): string {
  const n = scNonce();
  const isRemote = current.length > 0;
  const currentLabel = isRemote
    ? `Shared remote — <code>${scEscape(current)}</code>`
    : "On this machine only (local)";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Security-Policy"
        content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${n}';" />
  <style>
    body { font-family: var(--vscode-font-family); color: var(--vscode-foreground); padding: 16px 20px; max-width: 640px; }
    h2 { margin: 0 0 4px; font-size: 16px; }
    .sub { color: var(--vscode-descriptionForeground); font-size: 13px; margin: 0 0 14px; }
    .current { margin: 0 0 16px; padding: 8px 10px; border: 1px solid var(--vscode-panel-border); border-radius: 4px;
               background: var(--vscode-editorWidget-background, rgba(127,127,127,0.06)); font-size: 13px; }
    .current code { font-family: var(--vscode-editor-font-family, monospace); }
    fieldset { border: none; padding: 0; margin: 0; }
    .opt { margin: 10px 0 2px; }
    .opt label { font-weight: 600; cursor: pointer; }
    .hint { color: var(--vscode-descriptionForeground); font-size: 12px; margin: 0 0 6px 22px; }
    #url { width: calc(100% - 22px); margin: 4px 0 0 22px; box-sizing: border-box;
           font-family: var(--vscode-editor-font-family, monospace); font-size: 12px;
           color: var(--vscode-input-foreground); background: var(--vscode-input-background);
           border: 1px solid var(--vscode-input-border, var(--vscode-panel-border)); border-radius: 2px; padding: 4px 6px; }
    #url:disabled { opacity: 0.5; }
    .err { color: var(--vscode-errorForeground); font-size: 12px; margin: 10px 0 0; min-height: 16px; }
    .actions { margin-top: 18px; display: flex; gap: 8px; }
    button { font-family: inherit; color: var(--vscode-button-foreground); background: var(--vscode-button-background);
             border: none; padding: 5px 14px; cursor: pointer; border-radius: 2px; font-size: 13px; }
    button:hover { background: var(--vscode-button-hoverBackground); }
    button.secondary { color: var(--vscode-button-secondaryForeground); background: var(--vscode-button-secondaryBackground); }
    button.secondary:hover { background: var(--vscode-button-secondaryHoverBackground); }
  </style>
</head>
<body>
  <h2>Config Repo Storage</h2>
  <p class="sub">Where this MessageFoundry config repo lives. Nothing is contacted here — you push later from the Source Control view.</p>
  <div class="current">Current: ${currentLabel}</div>
  <fieldset>
    <div class="opt"><label><input type="radio" name="mode" value="local" ${isRemote ? "" : "checked"} /> On this machine only</label></div>
    <div class="hint">Fine for a single-box (non-HA) engine, dev, or air-gapped work with no server.</div>
    <div class="opt"><label><input type="radio" name="mode" value="remote" ${isRemote ? "checked" : ""} /> Shared remote</label></div>
    <div class="hint">Recommended for high availability (multiple engine hosts), a team, or off-machine backup. Any git host, scp-style, or a local/UNC bare path.</div>
    <input id="url" type="text" value="${scEscape(current)}" placeholder="https://forgejo.example/org/cfg.git &middot; git@host:repo.git &middot; \\\\server\\repos\\cfg.git" ${isRemote ? "" : "disabled"} />
  </fieldset>
  <div class="err" id="err"></div>
  <div class="actions">
    <button id="save">Save</button>
    <button id="cancel" class="secondary">Cancel</button>
  </div>
  <script nonce="${n}">
    const vscode = acquireVsCodeApi();
    const url = document.getElementById('url');
    const err = document.getElementById('err');
    function mode() { return document.querySelector('input[name=mode]:checked').value; }
    function sync() { const remote = mode() === 'remote'; url.disabled = !remote; if (remote) url.focus(); }
    document.querySelectorAll('input[name=mode]').forEach(function (r) {
      r.addEventListener('change', function () { err.textContent = ''; sync(); });
    });
    document.getElementById('save').addEventListener('click', function () {
      err.textContent = '';
      vscode.postMessage({ command: 'save', mode: mode(), url: url.value });
    });
    document.getElementById('cancel').addEventListener('click', function () {
      vscode.postMessage({ command: 'cancel' });
    });
    window.addEventListener('message', function (e) {
      if (e.data && e.data.command === 'error') { err.textContent = e.data.text; }
    });
    sync();
  </script>
</body>
</html>`;
}

function logResult(label: string, res: { stdout: string; stderr: string }): void {
  out().appendLine(label);
  if (res.stdout.trim()) {
    out().appendLine(res.stdout.trim());
  }
  if (res.stderr.trim()) {
    out().appendLine(res.stderr.trim());
  }
}

// The first commit is the project's BASELINE snapshot. Rather than run `git commit` blind and let the
// freshly-installed hook block it with a bare "bypass with --no-verify" (which reads as a dead-end and
// teaches bypass on day one), we PRE-FLIGHT the same gate and branch on the result. Exit 0 iff no
// REQUIRED check failed — advisories (e.g. dead-config) print but never block (checks.py / __main__).
// A required failure doesn't stop the baseline: the seed is conventionally exempt, so we offer to
// commit it and fix forward, with the details one click away — never leading with --no-verify.
async function maybeFirstCommit(bin: string, ws: string): Promise<void> {
  const pick = await vscode.window.showInformationMessage(
    "Make the first commit now? MessageFoundry will run the checks first so you can see the results.",
    "Run checks & commit",
    "Skip",
  );
  if (pick !== "Run checks & commit") {
    return;
  }
  await git(bin, ["add", "-A"], ws);

  out().appendLine("--- pre-flight: messagefoundry check ---");
  const chk = await run(["check", "--config", configDir(), "--messages", messageSetsDir()], ws);
  logResult("", chk);

  if (chk.code === 0) {
    const res = await git(bin, ["commit", "-m", "Initial commit (MessageFoundry checks enabled)"], ws);
    logResult("--- baseline commit ---", res);
    if (res.code === 0) {
      void vscode.window.showInformationMessage(
        "MessageFoundry: baseline committed — all required checks passed. ✓",
      );
    } else {
      out().show();
      void vscode.window.showWarningMessage(
        "MessageFoundry: the commit hook reported an issue — see the 'MessageFoundry Checks' output.",
      );
    }
    return;
  }

  // A required check failed. Offer the baseline anyway (fix-forward) — the seed commit is the only one
  // exempted; every commit after it runs the hook.
  out().show();
  const choice = await vscode.window.showWarningMessage(
    "A required check hasn't passed yet. You can still commit this as your baseline snapshot — the checks run on every commit after it, so you can fix the flagged items next. Details are in the 'MessageFoundry Checks' output.",
    "Commit baseline anyway",
    "Show details",
    "Cancel",
  );
  if (choice === "Commit baseline anyway") {
    const res = await git(
      bin,
      ["commit", "-m", "Initial commit (MessageFoundry checks enabled)", "--no-verify"],
      ws,
    );
    logResult("--- baseline commit (seed, checks enforced from the next commit) ---", res);
    if (res.code === 0) {
      void vscode.window.showInformationMessage(
        "MessageFoundry: baseline committed. Checks are active for your next commit — fix the flagged items in 'MessageFoundry Checks' before then.",
      );
    } else {
      void vscode.window.showErrorMessage(`MessageFoundry: commit failed — ${res.stderr.trim()}`);
    }
  } else if (choice === "Show details") {
    out().show();
  }
}
