# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 MessageFoundry Organization and contributors
"""Generate an N-entry ``connections.toml`` config dir for the reload-latency path (B11 wall #5).

Config-reload latency is O(connections); the cleanest way to measure it is to **grow the connection
set across a reload** and time the quiesce-and-swap. This generator materializes a self-contained
config DIRECTORY:

* ``connections.toml`` — N data-authored inbound MLLP connections (the ADR 0007 desugar path: each
  entry desugars through the same ``inbound()`` factory) + one shared outbound to the sink, all bound
  by name to a shared code-first router/handler.
* ``shared_logic.py`` — the shared code-first router + handler + the shared outbound. A normal
  (non-``_``) config module so the loader loads it (its ``@router``/``@handler``/``outbound()`` then
  register the names the TOML's inbounds bind). **Routing/transform logic stays code-first** (CLAUDE.md
  §1 / ADR 0007: only the connection *transport config* is data); the TOML's ``router =`` simply names
  the code-first ``cs_reload_router``.

The runner serves a dir generated at ``N_before`` inbounds, then rewrites the ``connections.toml`` to
``N_after`` and times ``EngineClient.reload_config(dir)`` — the O(connections) cost.
"""

from __future__ import annotations

from pathlib import Path

# The shared code-first module the TOML's inbounds bind by name. ROUTING/TRANSFORM LOGIC STAYS
# CODE-FIRST (ADR 0007) — only the per-connection transport config lives in the generated TOML.
_SHARED_MODULE = '''# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 MessageFoundry Organization and contributors
"""Shared code-first router/handler/outbound for the connection-scale reload-latency TOML graph (B11).

A normal config module (loaded directly), so the ``@router``/``@handler``/``outbound()`` register the
names the data-authored inbounds in ``connections.toml`` bind by name. Trivial pass-through: route →
one handler → the one shared sink outbound.
"""

from __future__ import annotations

from messagefoundry import MLLP, Send, handler, outbound, router
from messagefoundry.config.models import RetryPolicy
from messagefoundry.parsing.message import Message, RawMessage

_RETRY = RetryPolicy(
    max_attempts=5, backoff_seconds=0.5, backoff_multiplier=2.0, max_backoff_seconds=5.0
)

outbound(
    "OB_CS_RELOAD_SINK",
    MLLP(host="{sink_host}", port={sink_port}, connect_timeout=2.0, timeout_seconds=5.0),
    retry=_RETRY,
)


@router("cs_reload_router")
def route(_msg: Message | RawMessage) -> list[str]:
    return ["cs_reload_handler"]


@handler("cs_reload_handler")
def handle(msg: Message | RawMessage) -> Send:
    return Send("OB_CS_RELOAD_SINK", msg)
'''


def _toml_for(count: int, base_port: int) -> str:
    """The ``connections.toml`` text for ``count`` data-authored inbound MLLP connections, each
    binding the shared code-first ``cs_reload_router`` (ADR 0007 transport-config-as-data)."""
    if count < 1:
        raise ValueError(f"count must be >= 1, got {count}")
    if base_port + count - 1 > 65535:
        raise ValueError(
            f"base_port {base_port} + count {count} runs past port 65535 (highest would be "
            f"{base_port + count - 1})"
        )
    lines = [
        "# Generated by harness/config/connscale/gen_toml.py — the B11 config-reload-latency graph.",
        "# Data-authored inbound transport config (ADR 0007); the router/handler logic stays",
        "# code-first in _shared.py. Synthetic + generic — no real partner/site/host.",
        "",
    ]
    for i in range(count):
        lines.append("[[inbound]]")
        lines.append(f'name      = "IB_CS_RELOAD_{i:05d}"')
        lines.append('transport = "mllp"')
        lines.append('router    = "cs_reload_router"')
        lines.append("  [inbound.settings]")
        lines.append(f"  port = {base_port + i}")
        lines.append("")
    return "\n".join(lines)


def write_config_dir(
    config_dir: str | Path, *, count: int, base_port: int, sink_host: str, sink_port: int
) -> Path:
    """Materialize a complete reload-latency config dir at ``config_dir`` (created if absent): write
    ``_shared.py`` (the code-first router/handler/outbound) once and ``connections.toml`` with
    ``count`` inbounds. Returns the directory path. Call again with a different ``count`` to REWRITE
    just the TOML for the grow-reload (``shared_logic.py`` is stable, so only the connection set
    changes)."""
    path = Path(config_dir)
    path.mkdir(parents=True, exist_ok=True)
    (path / "shared_logic.py").write_text(
        _SHARED_MODULE.format(sink_host=sink_host, sink_port=sink_port), encoding="utf-8"
    )
    (path / "connections.toml").write_text(_toml_for(count, base_port), encoding="utf-8")
    return path
