# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 MessageFoundry Organization and contributors
"""One-off: trace the flat-silhouette media/icon.png into a themeable currentColor SVG.

Stdlib only (zlib/struct). Decodes the indexed PNG, builds a foreground mask, prints an ASCII
preview to verify the shape, and emits an SVG whose path is run-length rectangles per row — so the
activity-bar glyph exactly matches icon.png but recolours per VS Code theme.
"""

from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path

SRC = Path("ide/media/icon.png")
GRID = 64  # downsample target (512 / 8)


def _chunks(data: bytes):
    i = 8
    while i < len(data):
        (length,) = struct.unpack(">I", data[i : i + 4])
        ctype = data[i + 4 : i + 8].decode("ascii")
        body = data[i + 8 : i + 8 + length]
        yield ctype, body
        i += 12 + length


def _paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    return b if pb <= pc else c


def decode_indexed(path: Path) -> tuple[int, int, list[list[int]]]:
    raw = path.read_bytes()
    width = height = 0
    idat = b""
    for ctype, body in _chunks(raw):
        if ctype == "IHDR":
            width, height, bit_depth, color_type = struct.unpack(">IIBB", body[:10])
            assert (bit_depth, color_type) == (8, 3), (bit_depth, color_type)
        elif ctype == "IDAT":
            idat += body
    data = zlib.decompress(idat)
    stride = width  # 1 byte/pixel (indexed, 8-bit)
    rows: list[list[int]] = []
    prev = bytearray(stride)
    pos = 0
    for _ in range(height):
        ftype = data[pos]
        pos += 1
        line = bytearray(data[pos : pos + stride])
        pos += stride
        if ftype == 1:  # Sub
            for x in range(1, stride):
                line[x] = (line[x] + line[x - 1]) & 0xFF
        elif ftype == 2:  # Up
            for x in range(stride):
                line[x] = (line[x] + prev[x]) & 0xFF
        elif ftype == 3:  # Average
            for x in range(stride):
                a = line[x - 1] if x else 0
                line[x] = (line[x] + ((a + prev[x]) >> 1)) & 0xFF
        elif ftype == 4:  # Paeth
            for x in range(stride):
                a = line[x - 1] if x else 0
                c = prev[x - 1] if x else 0
                line[x] = (line[x] + _paeth(a, prev[x], c)) & 0xFF
        rows.append(list(line))
        prev = line
    return width, height, rows


def main() -> int:
    width, height, rows = decode_indexed(SRC)
    bg = rows[0][0]  # corner palette index = background
    factor_x, factor_y = width // GRID, height // GRID
    # Block-majority downsample to a GRID x GRID foreground mask (1 = anvil).
    mask = [[0] * GRID for _ in range(GRID)]
    for gy in range(GRID):
        for gx in range(GRID):
            fg = 0
            tot = 0
            for yy in range(gy * factor_y, (gy + 1) * factor_y):
                row = rows[yy]
                for xx in range(gx * factor_x, (gx + 1) * factor_x):
                    tot += 1
                    if row[xx] != bg:
                        fg += 1
            mask[gy][gx] = 1 if fg * 2 >= tot else 0

    # ASCII preview (verify the shape before writing the SVG).
    print(f"{width}x{height}, bg index={bg}, grid={GRID}")
    for gy in range(GRID):
        print("".join("##" if mask[gy][gx] else "  " for gx in range(GRID)))

    # Emit a single path: one run-length rect per horizontal run of foreground cells.
    parts: list[str] = []
    for gy in range(GRID):
        gx = 0
        while gx < GRID:
            if mask[gy][gx]:
                start = gx
                while gx < GRID and mask[gy][gx]:
                    gx += 1
                parts.append(f"M{start} {gy}h{gx - start}v1h-{gx - start}z")
            else:
                gx += 1
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}" fill="currentColor">\n'
        "  <!-- Activity-bar mark: themeable (currentColor) trace of media/icon.png (the full-colour\n"
        "       brand icon). Generated by scripts/trace_icon.py. VS Code recolours it per theme. -->\n"
        f'  <path d="{"".join(parts)}" />\n'
        "</svg>\n"
    )
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("ide/media/icon.traced.svg")
    out.write_text(svg, encoding="utf-8")
    print(f"\nwrote {out} ({len(parts)} runs, {len(svg)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
