<#
.SYNOPSIS
    Install the CLAIM gate (commit-msg) in the SHARED .git/hooks — one copy governs every worktree at
    once. The LEDGER gate is no longer installed here; it runs via .pre-commit-config.yaml.

.DESCRIPTION
    `.git/hooks` lives in the COMMON git directory, which every linked worktree shares. So a single file
    there:

      * reaches ALL worktrees the instant it is written -- no branch, no merge, no propagation lag (a
        hook committed to a branch protects nothing until every other worktree merges it);
      * survives a branch switch in any of them (it sits outside every working tree); and
      * sees EVERY write route -- the Edit tool, a shell redirect, Set-Content, python -c, VS Code, a
        subagent -- because it inspects the TREE at commit time, not a tool call.

    That last property is why this exists alongside the worktree gate (scripts/hooks/worktree_gate.ps1):
    the worktree gate inspects tool arguments, so a file written by a shell command is invisible to it.
    This is that backstop.

    ⭐ WHY THE LEDGER GATE MOVED OUT OF HERE (2026-07-27). It used to be installed as a standalone
    .git/hooks/pre-commit. Two tools cannot both own that file: this script refused to overwrite a
    foreign hook, and `pre-commit install` responded by renaming ours to pre-commit.legacy and calling
    it from its own shim. That works on POSIX and FAILS ON WINDOWS -- pre-commit invokes the legacy hook
    from a Python subprocess, which cannot resolve `#!/bin/sh`:

        ExecutableNotFoundError: Executable `/bin/sh` not found

    Measured: every commit in the repo was blocked until the shim was uninstalled. Note that
    pre-commit.legacy EXISTING did not indicate success -- only a real commit did. The ledger gate is
    therefore a `local` hook in .pre-commit-config.yaml (id: ledger-gate) and pre-commit owns the file
    alone. Running this script now MIGRATES an old install by removing our standalone hook.

    TRADE-OFF, stated because it is real: the ledger gate's availability is now coupled to pre-commit
    being installed. This script warns loudly when it is not. The claim gate stays a commit-msg hook --
    only commit-msg receives the message file, so it cannot move.

    ledger_check.py is stdlib-only and imports nothing from messagefoundry, so it still runs in a
    worktree with no project .venv.

    Run from a plain terminal. `git commit --no-verify` bypasses both -- that is a guardrail, not a
    security boundary, and the --ci leg is the backstop for exactly that.

.EXAMPLE
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Status
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Status
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$common = (& git -C $RepoRoot rev-parse --path-format=absolute --git-common-dir).Trim()
if (-not $common) { throw "Not inside a git repository." }

$hooksPath = (& git -C $RepoRoot config --get core.hooksPath)
if ($hooksPath) {
    $hooksDir = if ([System.IO.Path]::IsPathRooted($hooksPath)) { $hooksPath } else { Join-Path $RepoRoot $hooksPath }
} else {
    $hooksDir = Join-Path $common "hooks"
}
$preCommit = Join-Path $hooksDir "pre-commit"
$marker = "MessageFoundry ledger gate"
# BACKLOG #309: the claim gate must be a COMMIT-MSG hook, not pre-commit -- pre-commit never receives the
# commit message, so a claim check bolted onto it would look installed and silently never fire.
$commitMsg = Join-Path $hooksDir "commit-msg"
$claimMarker = "MessageFoundry claim gate"
$prePush = Join-Path $hooksDir "pre-push"
$pushMarker = "MessageFoundry push guard"

if ($Status) {
    $stale = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))
    $claimInstalled = (Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw -EA SilentlyContinue) -match [regex]::Escape($claimMarker))
    # The ledger gate is a pre-commit hook now, so "is it armed" means "did pre-commit install its
    # shim" -- reporting on OUR marker would say 'not installed' for a perfectly healthy setup.
    $pcShim = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
    Write-Host "hooks dir  : $hooksDir"
    Write-Host "commit-msg : $(if ($claimInstalled) { 'INSTALLED (claim gate)' } elseif (Test-Path $commitMsg) { 'present, but NOT ours' } else { 'not installed' })"
    Write-Host "pre-commit : $(if ($pcShim) { 'pre-commit framework (carries the ledger gate + leak gate)' } elseif ($stale) { 'STALE standalone ledger hook -- re-run this script to migrate' } elseif (Test-Path $preCommit) { 'present, but NOT ours' } else { 'NOT INSTALLED -- run: pre-commit install' })"
    if ($stale) {
        Write-Host "             ^ a leftover standalone hook will make `pre-commit install` chain to" -ForegroundColor Yellow
        Write-Host "               pre-commit.legacy, which FAILS on Windows and blocks every commit." -ForegroundColor Yellow
    }
    $pushInstalled = (Test-Path $prePush) -and ((Get-Content $prePush -Raw -EA SilentlyContinue) -match [regex]::Escape($pushMarker))
    Write-Host "pre-push   : $(if ($pushInstalled) { 'INSTALLED (push guard)' } elseif (Test-Path $prePush) { 'present, but NOT ours' } else { 'NOT INSTALLED' })"
    # Report the worktree-aware patch explicitly. Unpatched is not cosmetic: the shim's INSTALL_PYTHON
    # can point at a worktree that no longer exists (blocking every commit everywhere), and the
    # `language: system` ruff/bandit hooks only resolve from an activated shell.
    if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'MessageFoundry local patch \(worktree-aware toolchain\)')) {
        Write-Host "  patch    : worktree-aware (resolves .venv + INSTALL_PYTHON from the CURRENT worktree)"
    } elseif ($pcShim) {
        Write-Host "  patch    : NOT APPLIED -- run this script to fix" -ForegroundColor Yellow
        # (?m) so ^ anchors per LINE: Get-Content -Raw yields one string, and piping that to
        # Select-String with a ^ anchor silently matches nothing -- the diagnostic would just vanish.
        if ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match "(?m)^INSTALL_PYTHON='(.+)'\s*$") {
            $pinnedPy = $Matches[1]
            Write-Host "             INSTALL_PYTHON is hardcoded to $pinnedPy" -ForegroundColor Yellow
            if (-not (Test-Path $pinnedPy)) {
                Write-Host "             ^ THAT PATH DOES NOT EXIST -- commits are relying on the PATH fallback." -ForegroundColor Red
            } else {
                Write-Host "             If that checkout is ever removed, EVERY commit in EVERY worktree fails." -ForegroundColor Yellow
            }
        }
        Write-Host "             ruff/bandit are `language: system` -- they need the venv on PATH." -ForegroundColor Yellow
    }
    # A worktree whose ruff drifts off constraints.lock lints with a DIFFERENT linter than CI, and its
    # `ruff check --fix` hook rewrites files accordingly. Compare rather than assume.
    $wantRuff = (Select-String -Path (Join-Path $RepoRoot "constraints.lock") -Pattern '^ruff==(\S+)' -EA SilentlyContinue)
    if ($wantRuff) {
        $want = $wantRuff.Matches[0].Groups[1].Value
        $ruffExe = Join-Path $RepoRoot ".venv\Scripts\ruff.exe"
        if (-not (Test-Path $ruffExe)) { $ruffExe = Join-Path $RepoRoot ".venv/bin/ruff" }
        if (Test-Path $ruffExe) {
            $have = ((& $ruffExe --version) -split '\s+')[1]
            if ($have -eq $want) {
                Write-Host "ruff       : $have (matches constraints.lock)"
            } else {
                Write-Host "ruff       : $have but constraints.lock pins $want -- THIS WORKTREE LINTS DIFFERENTLY THAN CI" -ForegroundColor Red
                Write-Host "             Fix: .venv\Scripts\python.exe -m pip install `"ruff==$want`"" -ForegroundColor Red
            }
        } else {
            Write-Host "ruff       : not installed in this worktree's .venv (constraints.lock pins $want)" -ForegroundColor Yellow
        }
    }
    Write-Host "worktrees  : $(@(& git -C $RepoRoot worktree list).Count) share these hooks"
    return
}

if ($Uninstall) {
    $removed = $false
    if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $preCommit -Force
        Write-Host "Ledger pre-commit hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -match [regex]::Escape($claimMarker))) {
        Remove-Item -LiteralPath $commitMsg -Force
        Write-Host "Claim commit-msg hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if ((Test-Path $prePush) -and ((Get-Content $prePush -Raw) -match [regex]::Escape($pushMarker))) {
        Remove-Item -LiteralPath $prePush -Force
        Write-Host "Push guard pre-push hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if (-not $removed) { Write-Host "Nothing to remove (no MessageFoundry hooks installed)." }
    return
}

if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -notmatch [regex]::Escape($claimMarker))) {
    throw "A commit-msg hook that is not ours already exists at $commitMsg. Refusing to overwrite it -- merge them by hand."
}
if ((Test-Path $prePush) -and ((Get-Content $prePush -Raw) -notmatch [regex]::Escape($pushMarker))) {
    throw "A pre-push hook that is not ours already exists at $prePush. Refusing to overwrite it -- merge them by hand."
}

New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null

# --- MIGRATION: retire our OWN old pre-commit hook -------------------------------------------------
# The ledger gate used to be installed here as a standalone .git/hooks/pre-commit. It now runs as a
# `local` hook inside .pre-commit-config.yaml instead. Leaving the old copy in place is NOT harmless:
# `pre-commit install` would find a foreign hook, move it to pre-commit.legacy and call it from its own
# shim -- which fails on Windows (see the note below) and blocks EVERY commit. Remove ours; never touch
# a hook that is not ours.
if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
    Remove-Item -LiteralPath $preCommit -Force
    $legacy = "$preCommit.legacy"
    if ((Test-Path $legacy) -and ((Get-Content $legacy -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $legacy -Force
    }
    Write-Host "Migrated: the standalone ledger pre-commit hook was REMOVED." -ForegroundColor Yellow
    Write-Host "          The ledger gate now runs via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Yellow
}
Remove-Item -LiteralPath (Join-Path $hooksDir "ledger_check.py") -Force -EA SilentlyContinue

# --- claim gate (BACKLOG #309) -------------------------------------------------------------------
# A commit-msg hook, because only commit-msg is handed the message file (as $1). The claim gate keys off
# the SUBJECT declaring `BACKLOG #N`, so on pre-commit it would have nothing to read.
Copy-Item (Join-Path $RepoRoot "scripts\hooks\claim_check.py") (Join-Path $hooksDir "claim_check.py") -Force

$claimHook = @'
#!/bin/sh
# MessageFoundry claim gate -- INSTALLED COPY. Source: scripts/hooks/claim_check.py
# commit-msg (NOT pre-commit): only this hook receives the message file, and the gate reads the subject.
# Re-install after changing the source:  pwsh -NoProfile -File scripts/coord/install-git-hooks.ps1
HOOK_DIR=$(dirname "$0")
PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found -- THE CLAIM GATE IS OFF for this commit." >&2
  exit 0
fi
exec "$PY" "$HOOK_DIR/claim_check.py" "$1"
'@ -replace "`r`n", "`n"

[System.IO.File]::WriteAllText($commitMsg, $claimHook, (New-Object System.Text.UTF8Encoding $false))

# --- push guard ------------------------------------------------------------------------------------
# Since the MEFORORG cutover this repo IS the published artifact -- a push to main is publication, with
# no publish step left to catch anything. Server-side protection requires a PR and 12 checks, but
# enforce_admins is false, so the owner bypasses all of it and VS Code's Sync button does not
# distinguish main from a feature branch. This restores the class of protection the old mirror clone's
# Gate-Provenance pre-push hook provided before it was quarantined at cutover.
Copy-Item (Join-Path $RepoRoot "scripts\hooks\push_guard.py") (Join-Path $hooksDir "push_guard.py") -Force

$pushHook = @'
#!/bin/sh
# MessageFoundry push guard -- INSTALLED COPY. Source: scripts/hooks/push_guard.py
# Refuses a DIRECT push (or delete) of a protected branch. git feeds the refs on stdin.
# Re-install after changing the source:  pwsh -NoProfile -File scripts/coord/install-git-hooks.ps1
HOOK_DIR=$(dirname "$0")
PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found -- THE PUSH GUARD IS OFF for this push." >&2
  exit 0
fi
exec "$PY" "$HOOK_DIR/push_guard.py" "$@"
'@ -replace "`r`n", "`n"

[System.IO.File]::WriteAllText($prePush, $pushHook, (New-Object System.Text.UTF8Encoding $false))

# --- make pre-commit's generated shim WORKTREE-AWARE ----------------------------------------------
# pre-commit generates ONE .git/hooks/pre-commit, and because it lives in the common git dir every
# worktree runs it. It is generated with two assumptions that a multi-worktree checkout breaks:
#
#   1. INSTALL_PYTHON is hardcoded to whichever checkout happened to run `pre-commit install` -- here it
#      was MessageFoundry-ledger's .venv, a DISPOSABLE worktree. Remove that worktree and the fallback
#      `command -v pre-commit` finds nothing on a bare PATH, so EVERY commit in EVERY worktree exits 1.
#      Fails closed rather than open, but it blocks every session at once.
#   2. The ruff/bandit hooks are `language: system` -- deliberately, so pre-commit can never disagree
#      with the CI/dev ruff on a version (.pre-commit-config.yaml says so). But `language: system`
#      resolves the entry from PATH, and PATH holds no venv unless the user activated one. Measured
#      2026-07-29 from a bare PATH: `ruff` not found, so the ruff hooks fail. The symptom looks like a
#      broken hook; the cause is an unactivated shell.
#
# Worse than either alone: a worktree whose .venv drifts off constraints.lock silently lints with a
# DIFFERENT ruff than CI. That happened -- one worktree carried ruff 0.16.0 against pyproject's
# `<0.16` cap (installed standalone, so nothing capped it), producing ~829 findings CI does not have,
# and its `ruff check --fix` hook then STRIPPED `# noqa` directives the pinned ruff still wants.
#
# So resolve both against the worktree being committed in. `language: system` then gets exactly what
# that worktree's venv holds -- which is what the config always intended.
#
# Idempotent and marker-guarded: safe to re-run, and a no-op once applied. `pre-commit install`
# regenerates the file from scratch and drops this, so re-run this script after doing that.
$pcPatchMarker = "MessageFoundry local patch (worktree-aware toolchain)"
$pcPatch = @'

# --- MessageFoundry local patch (worktree-aware toolchain) ----------------------------------------
# Injected by scripts/coord/install-git-hooks.ps1 -- see that script for the full rationale.
# `pre-commit install` REGENERATES this file and removes this block; re-run the script afterwards.
_mf_root="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -n "$_mf_root" ]; then
    # Put THIS worktree's venv first on PATH so `language: system` hooks (ruff, bandit) resolve to the
    # same versions its tests and CI use, from any shell, activated or not.
    for _mf_dir in "$_mf_root/.venv/Scripts" "$_mf_root/.venv/bin"; do
        if [ -d "$_mf_dir" ]; then
            # POSIX-ify: a bare `C:/...` entry in a colon-separated PATH is ambiguous. cygpath ships
            # with Git for Windows; if it is somehow missing, skip rather than corrupt PATH.
            if command -v cygpath >/dev/null 2>&1; then
                _mf_dir="$(cygpath -u "$_mf_dir")"
            fi
            case ":$PATH:" in
                *":$_mf_dir:"*) ;;
                *) PATH="$_mf_dir:$PATH"; export PATH ;;
            esac
            break
        fi
    done
    # Run pre-commit itself from this worktree's interpreter when it has one, so the framework is never
    # tied to a worktree that can be deleted. The templated value above stays as the last resort.
    for _mf_py in "$_mf_root/.venv/Scripts/python.exe" "$_mf_root/.venv/bin/python"; do
        if [ -x "$_mf_py" ]; then
            INSTALL_PYTHON="$_mf_py"
            break
        fi
    done
fi
# --- end MessageFoundry local patch ---------------------------------------------------------------
'@ -replace "`r`n", "`n"

$pcIsFramework = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
if (-not $pcIsFramework) {
    # Never fabricate the file: without pre-commit's own shim there is nothing to patch, and the loud
    # "LEDGER GATE IS NOT ARMED" warning below is the correct signal.
    Write-Host "pre-commit shim absent -- skipping the worktree-aware patch (nothing to patch)." -ForegroundColor Yellow
} else {
    $pcBody = Get-Content $preCommit -Raw
    if ($pcBody -match [regex]::Escape($pcPatchMarker)) {
        Write-Host "pre-commit shim already worktree-aware (patch present) -- unchanged." -ForegroundColor DarkGray
    } elseif ($pcBody -notmatch '# end templated') {
        # Anchor missing => pre-commit changed its template. Refuse rather than guess at an insertion
        # point: a patch spliced into the wrong place could break every commit in every worktree.
        Write-Host "!! pre-commit's shim has no '# end templated' anchor -- NOT patching." -ForegroundColor Red
        Write-Host "   Its template changed. Re-check scripts/coord/install-git-hooks.ps1 against the" -ForegroundColor Red
        Write-Host "   generated file before relying on worktree-aware tool resolution." -ForegroundColor Red
    } else {
        # Insert immediately after the templated block, so INSTALL_PYTHON is overridden after pre-commit
        # sets it but before the exec that uses it.
        #
        # String.Replace, NOT -replace. In .NET regex replacement `$_` means THE ENTIRE INPUT STRING,
        # and this patch contains `$_mf_dir` / `$_mf_py` / `$_mf_root` -- so `-replace` spliced the whole
        # hook file into itself at each one (measured: 681 bytes -> 9556, with `PATH="#!/bin/sh...`
        # written into the middle of the PATH assignment). A corrupted pre-commit hook breaks commits in
        # all worktrees at once, so this is a literal replace with no substitution semantics.
        $anchor = "# end templated"
        $anchorCount = ([regex]::Matches($pcBody, [regex]::Escape($anchor))).Count
        if ($anchorCount -ne 1) {
            Write-Host "!! found $anchorCount '$anchor' anchors (expected 1) -- NOT patching." -ForegroundColor Red
            return
        }
        $patched = $pcBody.Replace($anchor, $anchor + $pcPatch)
        if ($patched -eq $pcBody) {
            Write-Host "!! could not splice the worktree-aware patch -- pre-commit shim left UNCHANGED." -ForegroundColor Red
        } else {
            Copy-Item -LiteralPath $preCommit -Destination "$preCommit.prepatch" -Force
            [System.IO.File]::WriteAllText($preCommit, ($patched -replace "`r`n", "`n"), (New-Object System.Text.UTF8Encoding $false))
            Write-Host "pre-commit shim PATCHED to be worktree-aware (backup: pre-commit.prepatch)." -ForegroundColor Green
        }
    }
}

# Git for Windows does not need the exec bit, but a WSL/Linux checkout of the same repo would.
if ($IsLinux -or $IsMacOS) { & chmod +x $commitMsg; & chmod +x $prePush }

Write-Host ""
Write-Host "MessageFoundry hooks INSTALLED." -ForegroundColor Green
Write-Host "  commit-msg: $commitMsg"
Write-Host "              $(Join-Path $hooksDir 'claim_check.py')   (claim gate, BACKLOG #309)"
Write-Host "  pre-push  : $prePush"
Write-Host "              $(Join-Path $hooksDir 'push_guard.py')    (refuses a direct push to main)"
Write-Host "  governs   : all $(@(& git -C $RepoRoot worktree list).Count) worktree(s) of this repo, immediately"
Write-Host ""

# The ledger gate now rides on pre-commit. If pre-commit is not installed, say so LOUDLY -- a gate that
# is simply absent looks identical to one that passed.
$pcInstalled = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
if ($pcInstalled) {
    Write-Host "Ledger gate: ARMED via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Green
} else {
    Write-Host "!! LEDGER GATE IS NOT ARMED." -ForegroundColor Red
    Write-Host "   It runs as a pre-commit hook now, and pre-commit is not installed in this repo." -ForegroundColor Red
    Write-Host "   Nothing is stopping two sessions colliding on an ADR/BACKLOG number. Fix with:" -ForegroundColor Red
    Write-Host "       pip install pre-commit" -ForegroundColor Red
    Write-Host "       pre-commit install" -ForegroundColor Red
    Write-Host ""
}
Write-Host "Ledger gate: blocks a commit that reuses an ADR/BACKLOG number, or adds an ADR with no index row."
Write-Host "Claim gate : blocks a CODE commit whose subject says 'BACKLOG #N' unless THIS worktree claims N,"
Write-Host "             so two sessions cannot build the same item in parallel. Docs-only commits pass."
Write-Host ""
Write-Host "Allocate numbers with:  pwsh -NoProfile -File scripts\coord\alloc.ps1 -Kind adr -Title `"<title>`""
Write-Host "Claim work with:        pwsh -NoProfile -File scripts\coord\claim.ps1 -Take <key> -Note `"<what>`""
Write-Host "See who holds what:     pwsh -NoProfile -File scripts\coord\claim.ps1 -List"
Write-Host "Remove with:            pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall"
