<#
.SYNOPSIS
    Install the CLAIM gate (commit-msg) in the SHARED .git/hooks — one copy governs every worktree at
    once. The LEDGER gate is no longer installed here; it runs via .pre-commit-config.yaml.

.DESCRIPTION
    `.git/hooks` lives in the COMMON git directory, which every linked worktree shares. So a single file
    there:

      * reaches ALL worktrees the instant it is written -- no branch, no merge, no propagation lag (a
        hook committed to a branch protects nothing until every other worktree merges it);
      * survives a branch switch in any of them (it sits outside every working tree); and
      * sees EVERY write route -- the Edit tool, a shell redirect, Set-Content, python -c, VS Code, a
        subagent -- because it inspects the TREE at commit time, not a tool call.

    That last property is why this exists alongside the worktree gate (scripts/hooks/worktree_gate.ps1):
    the worktree gate inspects tool arguments, so a file written by a shell command is invisible to it.
    This is that backstop.

    ⭐ WHY THE LEDGER GATE MOVED OUT OF HERE (2026-07-27). It used to be installed as a standalone
    .git/hooks/pre-commit. Two tools cannot both own that file: this script refused to overwrite a
    foreign hook, and `pre-commit install` responded by renaming ours to pre-commit.legacy and calling
    it from its own shim. That works on POSIX and FAILS ON WINDOWS -- pre-commit invokes the legacy hook
    from a Python subprocess, which cannot resolve `#!/bin/sh`:

        ExecutableNotFoundError: Executable `/bin/sh` not found

    Measured: every commit in the repo was blocked until the shim was uninstalled. Note that
    pre-commit.legacy EXISTING did not indicate success -- only a real commit did. The ledger gate is
    therefore a `local` hook in .pre-commit-config.yaml (id: ledger-gate) and pre-commit owns the file
    alone. Running this script now MIGRATES an old install by removing our standalone hook.

    TRADE-OFF, stated because it is real: the ledger gate's availability is now coupled to pre-commit
    being installed. This script warns loudly when it is not. The claim gate stays a commit-msg hook --
    only commit-msg receives the message file, so it cannot move.

    ledger_check.py is stdlib-only and imports nothing from messagefoundry, so it still runs in a
    worktree with no project .venv.

    Run from a plain terminal. `git commit --no-verify` bypasses both -- that is a guardrail, not a
    security boundary, and the --ci leg is the backstop for exactly that.

.EXAMPLE
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Status
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Status
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$common = (& git -C $RepoRoot rev-parse --path-format=absolute --git-common-dir).Trim()
if (-not $common) { throw "Not inside a git repository." }

$hooksPath = (& git -C $RepoRoot config --get core.hooksPath)
if ($hooksPath) {
    $hooksDir = if ([System.IO.Path]::IsPathRooted($hooksPath)) { $hooksPath } else { Join-Path $RepoRoot $hooksPath }
} else {
    $hooksDir = Join-Path $common "hooks"
}
$preCommit = Join-Path $hooksDir "pre-commit"
$marker = "MessageFoundry ledger gate"
# BACKLOG #309: the claim gate must be a COMMIT-MSG hook, not pre-commit -- pre-commit never receives the
# commit message, so a claim check bolted onto it would look installed and silently never fire.
$commitMsg = Join-Path $hooksDir "commit-msg"
$claimMarker = "MessageFoundry claim gate"
$prePush = Join-Path $hooksDir "pre-push"
$pushMarker = "MessageFoundry push guard"

if ($Status) {
    $stale = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))
    $claimInstalled = (Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw -EA SilentlyContinue) -match [regex]::Escape($claimMarker))
    # The ledger gate is a pre-commit hook now, so "is it armed" means "did pre-commit install its
    # shim" -- reporting on OUR marker would say 'not installed' for a perfectly healthy setup.
    $pcShim = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
    Write-Host "hooks dir  : $hooksDir"
    Write-Host "commit-msg : $(if ($claimInstalled) { 'INSTALLED (claim gate)' } elseif (Test-Path $commitMsg) { 'present, but NOT ours' } else { 'not installed' })"
    Write-Host "pre-commit : $(if ($pcShim) { 'pre-commit framework (carries the ledger gate + leak gate)' } elseif ($stale) { 'STALE standalone ledger hook -- re-run this script to migrate' } elseif (Test-Path $preCommit) { 'present, but NOT ours' } else { 'NOT INSTALLED -- run: pre-commit install' })"
    if ($stale) {
        Write-Host "             ^ a leftover standalone hook will make `pre-commit install` chain to" -ForegroundColor Yellow
        Write-Host "               pre-commit.legacy, which FAILS on Windows and blocks every commit." -ForegroundColor Yellow
    }
    $pushInstalled = (Test-Path $prePush) -and ((Get-Content $prePush -Raw -EA SilentlyContinue) -match [regex]::Escape($pushMarker))
    Write-Host "pre-push   : $(if ($pushInstalled) { 'INSTALLED (push guard)' } elseif (Test-Path $prePush) { 'present, but NOT ours' } else { 'NOT INSTALLED' })"
    # Report WHERE the shim's interpreter points. This script does not (and must not) rewrite that file
    # -- see the "DIAGNOSE, never write" note below -- so this is a diagnostic with a remedy, not a
    # pending action. It matters because the path is baked in at `pre-commit install` time and can name
    # a worktree that no longer exists, which fails every commit in every worktree at once.
    #
    # (?m) so ^ anchors per LINE: Get-Content -Raw yields ONE string, and piping that to Select-String
    # with a ^ anchor silently matches nothing -- the diagnostic would just vanish (it did).
    if ($pcShim -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match "(?m)^INSTALL_PYTHON='(.+)'\s*$")) {
        $pinnedPy = $Matches[1]
        # The PRIMARY checkout is the only non-disposable one: it owns the common git dir, so it cannot
        # be `git worktree remove`d. Anything else -- a sibling clone-style worktree like
        # MessageFoundry-ledger just as much as one under .claude/worktrees/ -- can vanish. Testing for
        # a `.claude\worktrees\` path missed exactly that case, so derive the primary from $common
        # instead of pattern-matching a layout convention.
        $primaryRoot = (Split-Path -Parent $common)
        # EXACT match against the primary's own venv, not a path-prefix test. Three traps, all hit while
        # writing this:
        #   * `"...\MessageFoundry-ledger\...".StartsWith("...\MessageFoundry")` is TRUE, so a bare
        #     prefix test reports a SIBLING worktree as the primary.
        #   * git returns the common dir with FORWARD slashes (C:/Users/...) while INSTALL_PYTHON uses
        #     backslashes, so an un-normalised compare never matches at all.
        #   * even a boundary-correct prefix test is wrong here: a worktree under
        #     `<primary>\.claude\worktrees\<name>` is INSIDE the primary's path and is still removable.
        #     Only the primary's own `.venv` is non-removable, so compare against exactly that.
        $normPinned = [System.IO.Path]::GetFullPath($pinnedPy)
        $primaryVenvPys = @(
            (Join-Path $primaryRoot ".venv\Scripts\python.exe"),
            (Join-Path $primaryRoot ".venv/bin/python")
        ) | ForEach-Object { [System.IO.Path]::GetFullPath($_) }
        if (-not (Test-Path $pinnedPy)) {
            Write-Host "  interp   : $pinnedPy" -ForegroundColor Red
            Write-Host "             ^ DOES NOT EXIST. Commits now depend on ``pre-commit`` being on PATH," -ForegroundColor Red
            Write-Host "               and on a bare PATH it is not. Fix: run ``pre-commit install`` from" -ForegroundColor Red
            Write-Host "               $primaryRoot" -ForegroundColor Red
        } elseif ($primaryVenvPys -notcontains $normPinned) {
            Write-Host "  interp   : $pinnedPy" -ForegroundColor Yellow
            Write-Host "             ^ NOT the primary checkout, so that worktree is removable. If it goes," -ForegroundColor Yellow
            Write-Host "               every commit in all $(@(& git -C $RepoRoot worktree list).Count) worktrees fails at once (it fails closed)." -ForegroundColor Yellow
            Write-Host "               Re-anchor: run ``pre-commit install`` from $primaryRoot" -ForegroundColor Yellow
        } else {
            Write-Host "  interp   : $pinnedPy (primary checkout -- not removable)"
        }
    }
    # A worktree whose ruff drifts off constraints.lock lints with a DIFFERENT linter than CI, and its
    # `ruff check --fix` hook rewrites files accordingly. Compare rather than assume.
    $wantRuff = (Select-String -Path (Join-Path $RepoRoot "constraints.lock") -Pattern '^ruff==(\S+)' -EA SilentlyContinue)
    if ($wantRuff) {
        $want = $wantRuff.Matches[0].Groups[1].Value
        $ruffExe = Join-Path $RepoRoot ".venv\Scripts\ruff.exe"
        if (-not (Test-Path $ruffExe)) { $ruffExe = Join-Path $RepoRoot ".venv/bin/ruff" }
        if (Test-Path $ruffExe) {
            $have = ((& $ruffExe --version) -split '\s+')[1]
            if ($have -eq $want) {
                Write-Host "ruff       : $have (matches constraints.lock)"
            } else {
                Write-Host "ruff       : $have but constraints.lock pins $want -- THIS WORKTREE LINTS DIFFERENTLY THAN CI" -ForegroundColor Red
                Write-Host "             Fix: .venv\Scripts\python.exe -m pip install `"ruff==$want`"" -ForegroundColor Red
            }
        } else {
            Write-Host "ruff       : not installed in this worktree's .venv (constraints.lock pins $want)" -ForegroundColor Yellow
        }
    }
    Write-Host "worktrees  : $(@(& git -C $RepoRoot worktree list).Count) share these hooks"
    return
}

if ($Uninstall) {
    $removed = $false
    if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $preCommit -Force
        Write-Host "Ledger pre-commit hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -match [regex]::Escape($claimMarker))) {
        Remove-Item -LiteralPath $commitMsg -Force
        Write-Host "Claim commit-msg hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if ((Test-Path $prePush) -and ((Get-Content $prePush -Raw) -match [regex]::Escape($pushMarker))) {
        Remove-Item -LiteralPath $prePush -Force
        Write-Host "Push guard pre-push hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if (-not $removed) { Write-Host "Nothing to remove (no MessageFoundry hooks installed)." }
    return
}

if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -notmatch [regex]::Escape($claimMarker))) {
    throw "A commit-msg hook that is not ours already exists at $commitMsg. Refusing to overwrite it -- merge them by hand."
}
if ((Test-Path $prePush) -and ((Get-Content $prePush -Raw) -notmatch [regex]::Escape($pushMarker))) {
    throw "A pre-push hook that is not ours already exists at $prePush. Refusing to overwrite it -- merge them by hand."
}

New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null

# --- MIGRATION: retire our OWN old pre-commit hook -------------------------------------------------
# The ledger gate used to be installed here as a standalone .git/hooks/pre-commit. It now runs as a
# `local` hook inside .pre-commit-config.yaml instead. Leaving the old copy in place is NOT harmless:
# `pre-commit install` would find a foreign hook, move it to pre-commit.legacy and call it from its own
# shim -- which fails on Windows (see the note below) and blocks EVERY commit. Remove ours; never touch
# a hook that is not ours.
if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
    Remove-Item -LiteralPath $preCommit -Force
    $legacy = "$preCommit.legacy"
    if ((Test-Path $legacy) -and ((Get-Content $legacy -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $legacy -Force
    }
    Write-Host "Migrated: the standalone ledger pre-commit hook was REMOVED." -ForegroundColor Yellow
    Write-Host "          The ledger gate now runs via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Yellow
}
Remove-Item -LiteralPath (Join-Path $hooksDir "ledger_check.py") -Force -EA SilentlyContinue

# --- claim gate (BACKLOG #309) -------------------------------------------------------------------
# A commit-msg hook, because only commit-msg is handed the message file (as $1). The claim gate keys off
# the SUBJECT declaring `BACKLOG #N`, so on pre-commit it would have nothing to read.
Copy-Item (Join-Path $RepoRoot "scripts\hooks\claim_check.py") (Join-Path $hooksDir "claim_check.py") -Force

$claimHook = @'
#!/bin/sh
# MessageFoundry claim gate -- INSTALLED COPY. Source: scripts/hooks/claim_check.py
# commit-msg (NOT pre-commit): only this hook receives the message file, and the gate reads the subject.
# Re-install after changing the source:  pwsh -NoProfile -File scripts/coord/install-git-hooks.ps1
HOOK_DIR=$(dirname "$0")
PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found -- THE CLAIM GATE IS OFF for this commit." >&2
  exit 0
fi
exec "$PY" "$HOOK_DIR/claim_check.py" "$1"
'@ -replace "`r`n", "`n"

[System.IO.File]::WriteAllText($commitMsg, $claimHook, (New-Object System.Text.UTF8Encoding $false))

# --- push guard ------------------------------------------------------------------------------------
# Since the MEFORORG cutover this repo IS the published artifact -- a push to main is publication, with
# no publish step left to catch anything. Server-side protection requires a PR and 12 checks, but
# enforce_admins is false, so the owner bypasses all of it and VS Code's Sync button does not
# distinguish main from a feature branch. This restores the class of protection the old mirror clone's
# Gate-Provenance pre-push hook provided before it was quarantined at cutover.
Copy-Item (Join-Path $RepoRoot "scripts\hooks\push_guard.py") (Join-Path $hooksDir "push_guard.py") -Force

$pushHook = @'
#!/bin/sh
# MessageFoundry push guard -- INSTALLED COPY. Source: scripts/hooks/push_guard.py
# Refuses a DIRECT push (or delete) of a protected branch. git feeds the refs on stdin.
# Re-install after changing the source:  pwsh -NoProfile -File scripts/coord/install-git-hooks.ps1
HOOK_DIR=$(dirname "$0")
PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found -- THE PUSH GUARD IS OFF for this push." >&2
  exit 0
fi
exec "$PY" "$HOOK_DIR/push_guard.py" "$@"
'@ -replace "`r`n", "`n"

[System.IO.File]::WriteAllText($prePush, $pushHook, (New-Object System.Text.UTF8Encoding $false))

# --- pre-commit's generated shim: DIAGNOSE, never write -------------------------------------------
# This script deliberately does NOT touch .git/hooks/pre-commit. pre-commit owns that file alone, and
# tests/test_ledger_check.py::test_the_installer_no_longer_writes_a_pre_commit_hook enforces it,
# because two tools contending for it once blocked EVERY commit in the repo on Windows (see the
# header). A patch here would also be futile: `pre-commit install` rewrites the file from its template,
# so anything spliced in is erased the next time anyone runs it.
#
# There are two real problems with the generated shim in a multi-worktree checkout. Both are REPORTED
# by -Status and both have a supported remedy that needs no patching:
#
#   1. INSTALL_PYTHON is hardcoded to whichever checkout last ran `pre-commit install` -- here it was
#      MessageFoundry-ledger's .venv, a DISPOSABLE worktree. Delete that worktree and the fallback
#      `command -v pre-commit` finds nothing on a bare PATH, so every commit in every worktree exits 1.
#      Fails closed, but blocks every session at once.
#      REMEDY: run `pre-commit install` from the PRIMARY checkout, whose .venv is not disposable. That
#      is pre-commit's own mechanism for repointing it -- no third-party edit to its file.
#
#   2. ruff/bandit/ledger-gate/forbidden-content are `language: system` -- deliberately, so pre-commit
#      cannot disagree with the CI/dev ruff on a version. But `language: system` resolves from PATH, so
#      the hooks need a venv on PATH. Measured from a bare PATH: `ruff` not found.
#      REMEDY: commit from a shell with the worktree's .venv activated (the documented workflow).
#
# The sharper half of (2) is version drift, not absence, and -Status checks it: a worktree whose ruff
# disagrees with constraints.lock lints with a DIFFERENT linter than CI *and* its `ruff check --fix`
# hook rewrites files to match. Measured 2026-07-29: one worktree carried ruff 0.16.0 against
# pyproject's `<0.16` cap (installed standalone, so nothing capped it), producing ~829 findings CI does
# not have, and stripping `# noqa` directives the pinned 0.15.22 still wants.

# Git for Windows does not need the exec bit, but a WSL/Linux checkout of the same repo would.
if ($IsLinux -or $IsMacOS) { & chmod +x $commitMsg; & chmod +x $prePush }

Write-Host ""
Write-Host "MessageFoundry hooks INSTALLED." -ForegroundColor Green
Write-Host "  commit-msg: $commitMsg"
Write-Host "              $(Join-Path $hooksDir 'claim_check.py')   (claim gate, BACKLOG #309)"
Write-Host "  pre-push  : $prePush"
Write-Host "              $(Join-Path $hooksDir 'push_guard.py')    (refuses a direct push to main)"
Write-Host "  governs   : all $(@(& git -C $RepoRoot worktree list).Count) worktree(s) of this repo, immediately"
Write-Host ""

# The ledger gate now rides on pre-commit. If pre-commit is not installed, say so LOUDLY -- a gate that
# is simply absent looks identical to one that passed.
$pcInstalled = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
if ($pcInstalled) {
    Write-Host "Ledger gate: ARMED via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Green
} else {
    Write-Host "!! LEDGER GATE IS NOT ARMED." -ForegroundColor Red
    Write-Host "   It runs as a pre-commit hook now, and pre-commit is not installed in this repo." -ForegroundColor Red
    Write-Host "   Nothing is stopping two sessions colliding on an ADR/BACKLOG number. Fix with:" -ForegroundColor Red
    Write-Host "       pip install pre-commit" -ForegroundColor Red
    Write-Host "       pre-commit install" -ForegroundColor Red
    Write-Host ""
}
Write-Host "Ledger gate: blocks a commit that reuses an ADR/BACKLOG number, or adds an ADR with no index row."
Write-Host "Claim gate : blocks a CODE commit whose subject says 'BACKLOG #N' unless THIS worktree claims N,"
Write-Host "             so two sessions cannot build the same item in parallel. Docs-only commits pass."
Write-Host ""
Write-Host "Allocate numbers with:  pwsh -NoProfile -File scripts\coord\alloc.ps1 -Kind adr -Title `"<title>`""
Write-Host "Claim work with:        pwsh -NoProfile -File scripts\coord\claim.ps1 -Take <key> -Note `"<what>`""
Write-Host "See who holds what:     pwsh -NoProfile -File scripts\coord\claim.ps1 -List"
Write-Host "Remove with:            pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall"
