<#
.SYNOPSIS
    Install the CLAIM gate (commit-msg) in the SHARED .git/hooks — one copy governs every worktree at
    once. The LEDGER gate is no longer installed here; it runs via .pre-commit-config.yaml.

.DESCRIPTION
    `.git/hooks` lives in the COMMON git directory, which every linked worktree shares. So a single file
    there:

      * reaches ALL worktrees the instant it is written -- no branch, no merge, no propagation lag (a
        hook committed to a branch protects nothing until every other worktree merges it);
      * survives a branch switch in any of them (it sits outside every working tree); and
      * sees EVERY write route -- the Edit tool, a shell redirect, Set-Content, python -c, VS Code, a
        subagent -- because it inspects the TREE at commit time, not a tool call.

    That last property is why this exists alongside the worktree gate (scripts/hooks/worktree_gate.ps1):
    the worktree gate inspects tool arguments, so a file written by a shell command is invisible to it.
    This is that backstop.

    ⭐ WHY THE LEDGER GATE MOVED OUT OF HERE (2026-07-27). It used to be installed as a standalone
    .git/hooks/pre-commit. Two tools cannot both own that file: this script refused to overwrite a
    foreign hook, and `pre-commit install` responded by renaming ours to pre-commit.legacy and calling
    it from its own shim. That works on POSIX and FAILS ON WINDOWS -- pre-commit invokes the legacy hook
    from a Python subprocess, which cannot resolve `#!/bin/sh`:

        ExecutableNotFoundError: Executable `/bin/sh` not found

    Measured: every commit in the repo was blocked until the shim was uninstalled. Note that
    pre-commit.legacy EXISTING did not indicate success -- only a real commit did. The ledger gate is
    therefore a `local` hook in .pre-commit-config.yaml (id: ledger-gate) and pre-commit owns the file
    alone. Running this script now MIGRATES an old install by removing our standalone hook.

    TRADE-OFF, stated because it is real: the ledger gate's availability is now coupled to pre-commit
    being installed. This script warns loudly when it is not. The claim gate stays a commit-msg hook --
    only commit-msg receives the message file, so it cannot move.

    ledger_check.py is stdlib-only and imports nothing from messagefoundry, so it still runs in a
    worktree with no project .venv.

    Run from a plain terminal. `git commit --no-verify` bypasses both -- that is a guardrail, not a
    security boundary, and the --ci leg is the backstop for exactly that.

.EXAMPLE
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Status
    pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [switch]$Uninstall,
    [switch]$Status
)

$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$common = (& git -C $RepoRoot rev-parse --path-format=absolute --git-common-dir).Trim()
if (-not $common) { throw "Not inside a git repository." }

$hooksPath = (& git -C $RepoRoot config --get core.hooksPath)
if ($hooksPath) {
    $hooksDir = if ([System.IO.Path]::IsPathRooted($hooksPath)) { $hooksPath } else { Join-Path $RepoRoot $hooksPath }
} else {
    $hooksDir = Join-Path $common "hooks"
}
$preCommit = Join-Path $hooksDir "pre-commit"
$marker = "MessageFoundry ledger gate"
# BACKLOG #309: the claim gate must be a COMMIT-MSG hook, not pre-commit -- pre-commit never receives the
# commit message, so a claim check bolted onto it would look installed and silently never fire.
$commitMsg = Join-Path $hooksDir "commit-msg"
$claimMarker = "MessageFoundry claim gate"

if ($Status) {
    $stale = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))
    $claimInstalled = (Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw -EA SilentlyContinue) -match [regex]::Escape($claimMarker))
    # The ledger gate is a pre-commit hook now, so "is it armed" means "did pre-commit install its
    # shim" -- reporting on OUR marker would say 'not installed' for a perfectly healthy setup.
    $pcShim = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
    Write-Host "hooks dir  : $hooksDir"
    Write-Host "commit-msg : $(if ($claimInstalled) { 'INSTALLED (claim gate)' } elseif (Test-Path $commitMsg) { 'present, but NOT ours' } else { 'not installed' })"
    Write-Host "pre-commit : $(if ($pcShim) { 'pre-commit framework (carries the ledger gate + leak gate)' } elseif ($stale) { 'STALE standalone ledger hook -- re-run this script to migrate' } elseif (Test-Path $preCommit) { 'present, but NOT ours' } else { 'NOT INSTALLED -- run: pre-commit install' })"
    if ($stale) {
        Write-Host "             ^ a leftover standalone hook will make `pre-commit install` chain to" -ForegroundColor Yellow
        Write-Host "               pre-commit.legacy, which FAILS on Windows and blocks every commit." -ForegroundColor Yellow
    }
    Write-Host "worktrees  : $(@(& git -C $RepoRoot worktree list).Count) share these hooks"
    return
}

if ($Uninstall) {
    $removed = $false
    if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $preCommit -Force
        Write-Host "Ledger pre-commit hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -match [regex]::Escape($claimMarker))) {
        Remove-Item -LiteralPath $commitMsg -Force
        Write-Host "Claim commit-msg hook REMOVED." -ForegroundColor Yellow
        $removed = $true
    }
    if (-not $removed) { Write-Host "Nothing to remove (no MessageFoundry hooks installed)." }
    return
}

if ((Test-Path $commitMsg) -and ((Get-Content $commitMsg -Raw) -notmatch [regex]::Escape($claimMarker))) {
    throw "A commit-msg hook that is not ours already exists at $commitMsg. Refusing to overwrite it -- merge them by hand."
}

New-Item -ItemType Directory -Force -Path $hooksDir | Out-Null

# --- MIGRATION: retire our OWN old pre-commit hook -------------------------------------------------
# The ledger gate used to be installed here as a standalone .git/hooks/pre-commit. It now runs as a
# `local` hook inside .pre-commit-config.yaml instead. Leaving the old copy in place is NOT harmless:
# `pre-commit install` would find a foreign hook, move it to pre-commit.legacy and call it from its own
# shim -- which fails on Windows (see the note below) and blocks EVERY commit. Remove ours; never touch
# a hook that is not ours.
if ((Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
    Remove-Item -LiteralPath $preCommit -Force
    $legacy = "$preCommit.legacy"
    if ((Test-Path $legacy) -and ((Get-Content $legacy -Raw -EA SilentlyContinue) -match [regex]::Escape($marker))) {
        Remove-Item -LiteralPath $legacy -Force
    }
    Write-Host "Migrated: the standalone ledger pre-commit hook was REMOVED." -ForegroundColor Yellow
    Write-Host "          The ledger gate now runs via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Yellow
}
Remove-Item -LiteralPath (Join-Path $hooksDir "ledger_check.py") -Force -EA SilentlyContinue

# --- claim gate (BACKLOG #309) -------------------------------------------------------------------
# A commit-msg hook, because only commit-msg is handed the message file (as $1). The claim gate keys off
# the SUBJECT declaring `BACKLOG #N`, so on pre-commit it would have nothing to read.
Copy-Item (Join-Path $RepoRoot "scripts\hooks\claim_check.py") (Join-Path $hooksDir "claim_check.py") -Force

$claimHook = @'
#!/bin/sh
# MessageFoundry claim gate -- INSTALLED COPY. Source: scripts/hooks/claim_check.py
# commit-msg (NOT pre-commit): only this hook receives the message file, and the gate reads the subject.
# Re-install after changing the source:  pwsh -NoProfile -File scripts/coord/install-git-hooks.ps1
HOOK_DIR=$(dirname "$0")
PY=python
command -v python >/dev/null 2>&1 || PY=python3
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "MessageFoundry: python not found -- THE CLAIM GATE IS OFF for this commit." >&2
  exit 0
fi
exec "$PY" "$HOOK_DIR/claim_check.py" "$1"
'@ -replace "`r`n", "`n"

[System.IO.File]::WriteAllText($commitMsg, $claimHook, (New-Object System.Text.UTF8Encoding $false))

# Git for Windows does not need the exec bit, but a WSL/Linux checkout of the same repo would.
if ($IsLinux -or $IsMacOS) { & chmod +x $commitMsg }

Write-Host ""
Write-Host "MessageFoundry claim gate INSTALLED." -ForegroundColor Green
Write-Host "  commit-msg: $commitMsg"
Write-Host "              $(Join-Path $hooksDir 'claim_check.py')   (claim gate, BACKLOG #309)"
Write-Host "  governs   : all $(@(& git -C $RepoRoot worktree list).Count) worktree(s) of this repo, immediately"
Write-Host ""

# The ledger gate now rides on pre-commit. If pre-commit is not installed, say so LOUDLY -- a gate that
# is simply absent looks identical to one that passed.
$pcInstalled = (Test-Path $preCommit) -and ((Get-Content $preCommit -Raw -EA SilentlyContinue) -match 'File generated by pre-commit')
if ($pcInstalled) {
    Write-Host "Ledger gate: ARMED via .pre-commit-config.yaml (id: ledger-gate)." -ForegroundColor Green
} else {
    Write-Host "!! LEDGER GATE IS NOT ARMED." -ForegroundColor Red
    Write-Host "   It runs as a pre-commit hook now, and pre-commit is not installed in this repo." -ForegroundColor Red
    Write-Host "   Nothing is stopping two sessions colliding on an ADR/BACKLOG number. Fix with:" -ForegroundColor Red
    Write-Host "       pip install pre-commit" -ForegroundColor Red
    Write-Host "       pre-commit install" -ForegroundColor Red
    Write-Host ""
}
Write-Host "Ledger gate: blocks a commit that reuses an ADR/BACKLOG number, or adds an ADR with no index row."
Write-Host "Claim gate : blocks a CODE commit whose subject says 'BACKLOG #N' unless THIS worktree claims N,"
Write-Host "             so two sessions cannot build the same item in parallel. Docs-only commits pass."
Write-Host ""
Write-Host "Allocate numbers with:  pwsh -NoProfile -File scripts\coord\alloc.ps1 -Kind adr -Title `"<title>`""
Write-Host "Claim work with:        pwsh -NoProfile -File scripts\coord\claim.ps1 -Take <key> -Note `"<what>`""
Write-Host "See who holds what:     pwsh -NoProfile -File scripts\coord\claim.ps1 -List"
Write-Host "Remove with:            pwsh -NoProfile -File scripts\coord\install-git-hooks.ps1 -Uninstall"
